export const HELP_TOPICS = Object.freeze([
  {
    id: "workspace-interface",
    title: "Workspace interface",
    keywords: "info panel documentation command palette sidebar bottom bar timeline outliner script assistant multiplayer properties settings canvas panels dock",
    body: "Underscores is an infinite creative computational canvas for performance, teaching, exploration, and research. It keeps the canvas quiet and moves controls into dockable panels. Use the command palette to find actions, then open Outliner, Script, Assistant, Multiplayer, Properties, Settings, Timeline, Info, or Documentation as needed. Panels can be moved, resized, collapsed, or restored from their edge handles.",
  },
  {
    id: "physics-formulas",
    title: "Physics mapping formulas",
    keywords: "formula mapping physics midi pitch velocity cc bend collision expression variables scale major minor pentatonic",
    body: "Formulas are safe expressions, not JavaScript. They support arithmetic, comparisons, &&, ||, !, parentheses, and if, abs, min, max, clamp, round, floor, ceil, pow.\n\nShared values: raw (selected source field), norm (normalized source range), value (mapped output), impulse, speed, x/y (contact point), normalX/normalY, aX/aY/aVx/aVy/aSpeed, bX/bY/bVx/bVy/bSpeed, gravityX/gravityY, worldTime, step, timeScale, simSpeed, pixelsPerMeter. Body material values are available as aMass/bMass, aFriction/bFriction, aBounce/bBounce, and aDensity/bDensity. Each physics object also has Object note, available as aNote/noteA and bNote/noteB.\n\nPitch formulas also receive baseNote. Scale helpers: major(root, degree), minor(root, degree), pentatonic(root, degree), and scale(root, degree, semitone0, ...).",
    examples: [
      "major(baseNote, floor(speed / 12))",
      "clamp(20 + speed * 2, 1, 127)",
      "round(clamp(8192 + normalX * 8191, 0, 16383))",
    ],
  },
  {
    id: "physics-marionette",
    title: "Physics marionette case study",
    keywords: "physics marionette paper doll bauhaus schlemmer rig body pin spring axle revolute live pose mouse wind chime collision expressive synth mediapipe t-pose history recording playback walkthrough",
    body: "The Marionette case study builds a Bauhaus-inspired paper doll from four ordinary Excalidraw primitives, then layers an articulated physics rig, collision sound, a second MediaPipe-driven visual rig, and History playback. Start `/walkthrough start physics-marionette-study-v1` for the seven-stage lesson, or run `/physics demo marionette` to jump directly to the complete starter. The generated Marionette world contains a world pin for the head, a damped neck spring, and revolute shoulder joints. Play the world and drag an unselected body or joint for a temporary live pose; Reset returns to the authored pose and Apply Current Pose commits a staged arrangement. Add a body-to-body Expressive Synth mapping to make contacts behave like wind chimes. Keep the physics doll running while a separate MediaPipe · Schlemmer pose p5 node provides a second rig; when no completed camera frame exists, the example falls back to a deterministic T-pose. Finally record a short gesture with History, stop the take, and use `/history play`, the playhead, export, or Create walkthrough to review and share it. The full classroom notes live in `notes/examples/physics-marionette.md`.",
    examples: [
      "/walkthrough start physics-marionette-study-v1",
      "const graph = __.api.relations.get();\nconst world = graph.systems.find(system => system.name === \"Marionette\");\nconst bodies = graph.bodies.filter(body => body.systemId === world?.id);\nconst joints = graph.constraints.filter(constraint => constraint.systemId === world?.id);",
      "await __.api.commands.execute(\"physics.mapping.create\", { collisionClass: \"body-body\", target: \"expressive-voice\" });",
      "const holistic = __.streams.list().find(stream => stream.kind === \"holistic\");\nconst nose = holistic?.feature(\"pose.nose\", { space: \"normalized\" });\nconst physics = __.api.physics;",
      "/record start\n/record stop\n/history play",
    ],
  },
  {
    id: "physics-mappings",
    title: "Physics collision mappings",
    keywords: "physics collision mapping source filter transform target midi expressive synth begin hit end stay contact body wall tags object",
    body: "Mappings run Source → Filter → Transform → Target without a React render. Source chooses a system, collision class, contact phase, tags or specific objects, and a numeric field. Filter rejects events by range or boolean formula. Transform maps the surviving value. Target sends MIDI Note, CC, Pitch Bend, or an Expressive Synth voice.\n\nUse hit for one note per impact. Use begin/end with a pair-gate target for notes or voices that persist while a pair is in contact. Stay is opt-in and drives continuous expressive updates while Contact stay events is enabled for the world.",
  },
  {
    id: "physics-debug",
    title: "Physics debug overlay",
    keywords: "physics debug overlay collider contacts collisions forces labels bodies springs constraints",
    body: "The Physics Debug Overlay is diagnostic-only and does not serialize as canvas art. Bodies and colliders show the geometry sent to Rapier; labels identify their runtime bodies. Contact markers show recent collision points, while force arrows show reported contact impulse. Enable only the filters needed while diagnosing a system.",
  },
  {
    id: "score",
    title: "Score roles",
    keywords: "score iannix curve cursor trigger transport midi role",
    body: "A Score combines curves, cursors, and triggers. Curves provide the path, cursors travel it in score time, and triggers emit messages at positions on a curve. Score roles are independent from physics roles; mappings and scripts can bridge their events when needed.",
  },
  {
    id: "media-streams",
    title: "Media streams and actors",
    keywords: "media stream mediapipe holistic camera actor brush input landmark source catalog clip recorder gif mp4 webm alpha audio download frame all loop",
    body: "Media sources stay dormant in the catalog until selected or connected to an enabled scene object. Select one to preview and play it, use Record clip to create GIF, MP4 with source audio, audio-only, or WebM alpha clips, and press Escape to clear selection. Canvas capture can target a frame, rectangle, or the full scene. A Holistic processor stores its source, transform, and display settings without creating one object per landmark. Use the Media and Inputs panels to create streams, then use actors, Brush channels, or scripts to consume them.",
  },
  {
    id: "script-parameters",
    title: "Script parameters",
    keywords: "parameter params param number string text color picker boolean bool json object canvas element p5 play core livecode brush iannix",
    body: "Shared @param declarations accept numbers, strings, CSS colors, booleans, parsed JSON values, and canvas object references. Numbers keep their range and step controls; colors use the compact in-app picker, live app/canvas eyedropper preview, and dynamic __ color references; JSON is edited as a JavaScript value and object references resolve through the canvas query API.",
  },
  {
    id: "livecode-compositing",
    title: "Livecode compositing",
    keywords: "livecode compositing composition layer underlay overlay blend opacity background transparent theme solid performance gpu fluid brush emission",
    body: "Every visual Livecode node can be composed without flattening its output. Layer places the node above or below native canvas objects; Opacity and Blend are browser-compositor properties; Background controls the host surface while preserving adapter-owned pixels. Defaults remain Above objects, 100%, Normal, and Adapter default, so an untouched node adds no extra blending work.\n\nLarge overlapping translucent or blended surfaces cost GPU fill-rate in proportion to their pixel area. Prefer Normal for nodes that do not need blending, keep full-canvas feedback nodes bounded, and avoid stacking many Retina-sized transparent surfaces. Composition never reads pixels back or writes scene state per frame.\n\nFluid Brush and Inkwash declare // @param emission = true (boolean). Emission lets the chosen scene or physics-debug geometry continuously inject and stir dye or wet pigment. Turn it off in Parameters to keep pointer painting while skipping geometry collection. Older patches with the former node setting remain compatible.",
    examples: [
      "layer underlay",
      "blend screen",
      "node opacity 65",
      "// @param emission = true (boolean)",
    ],
  },
  {
    id: "script-svg",
    title: "SVG quick reference",
    keywords: "svg quick reference path shape transform style viewbox source editor anchor bezier",
    body: "SVG nodes keep their source as editable text while exposing paths and shapes on the canvas. Use viewBox for document coordinates, path d commands for geometry, and currentColor or explicit CSS colors for styling. Command-click a rendered path to edit it; double-click a segment to insert an anchor, and use Properties or Outliner when you need a precise subpath selection.",
    examples: [
      "<svg viewBox=\"0 0 320 180\">",
      "<path d=\"M20 90 C80 20 240 160 300 90\" fill=\"none\" stroke=\"currentColor\" />",
    ],
  },
  {
    id: "script-p5",
    title: "p5 quick reference",
    keywords: "p5 quick reference livecode javascript sketch setup draw createcanvas params transparent frame reset mediapipe blobatar avatar mouse follow",
    body: "p5 sketches run as self-contained Livecode nodes. setup() runs once, draw() runs each frame, and __.element plus __.params connect the sketch to its host and declared controls. The Example menu includes MediaPipe · Blobatar: a small, theme-aware avatar whose body eases toward pose.nose and falls back to mouseX/mouseY when no Holistic frame is available. Change p5 version, transparent-surface, and frame-reset settings in Node settings when a sketch needs a different lifecycle.",
    examples: [
      "function setup() { createCanvas(__.element.width, __.element.height); }",
      "function draw() { circle(width / 2, height / 2, 80); }",
      "const body = __.streams.list().find(stream => stream.kind === \"holistic\");\nconst nose = body?.feature(\"pose.nose\", { space: \"normalized\" });\nconst x = nose?.position?.x * width || mouseX;",
    ],
  },
  {
    id: "script-glsl",
    title: "GLSL quick reference",
    keywords: "glsl quick reference livecode shader fragment blank template uv fc r t resolution composition",
    body: "GLSL nodes render fragment shaders into a composable Livecode surface. The standard inputs include FC.xy for the fragment coordinate, r.xy for the surface resolution, and t for shared time. Layer, surface opacity, blend, and background use the shared Livecode compositor. Fluid Brush and Inkwash expose Emission as a script parameter: it lets scene or physics-debug geometry continuously inject and stir dye while pointer painting remains available.",
    examples: [
      "vec2 uv = (FC.xy - 0.5 * r.xy) / r.y;",
      "o = vec4(0.1 + 0.4 * sin(t + uv.x), 0.25, 0.8, 1.0);",
    ],
  },
  {
    id: "script-play-core",
    title: "Play Core quick reference",
    keywords: "play core quick reference ascii frame program settings fps cols rows main context buffer",
    body: "Play Core programs render one ASCII cell at a time into a rectangle or frame. Export settings for fps, cols, rows, color, and backgroundColor, then return a character or cell object from main(coord, context). Use pre and post around a shared buffer when a program needs a frame-wide pass.",
    examples: [
      "export const settings = { fps: 30 };",
      "export function main({ x, y }, context) { return Math.sin(x + context.time / 400) > 0 ? \"·\" : \" \"; }",
    ],
  },
  {
    id: "script-orca",
    title: "Orca quick reference",
    keywords: "orca quick reference livecode grid operators notes clock linked free step",
    body: "Orca is a compact frame-based livecoding grid. Type directly into cells, use uppercase operators to transform the grid, and use note operators such as : or % to emit events. Linked clocks follow Timeline; free clocks advance while the node runs.",
    examples: ["..:03C..\n..*....\n..R...."],
  },
  {
    id: "script-score",
    title: "Score quick reference",
    keywords: "score quick reference iannix curve cursor trigger run commands setcurve setspeed sessiontime",
    body: "Scores combine named curves, cursors, and triggers. Create and configure them with run() commands; cursors travel curves in score time and triggers emit messages at curve positions. Completion lists the supported syntax and runnable examples for the active command.",
    examples: [
      "run(\"add curve orbit\")",
      "run(\"add cursor traveler\")",
      "run(\"setCurve traveler orbit\")",
    ],
  },
  {
    id: "script-brush",
    title: "Brush quick reference",
    keywords: "brush quick reference modifier points globals tracks params apply bake channel",
    body: "Brush modifiers receive point tracks and a globals object, then return transformed or replacement tracks. Declare @param values for editable controls. Brush channels can map typed input streams to a live stroke and commit the visible result as one undoable freedraw.",
    examples: ["(points, globals) => {\n  return [points];\n}"],
  },
  {
    id: "script-media",
    title: "Media streams quick reference",
    keywords: "media streams quick reference holistic mediapipe feature inputs mapping actors scene normalized schlemmer pose blobatar avatar t-pose fallback mouse",
    body: "Media sources feed previews, Canvas capture, Holistic processors, actors, and typed streams. Source pixels and device handles stay local; semantic observations can be read by scripts or routed through Inputs, Mapping, and Brush. The MediaPipe · Schlemmer pose p5 example reads named pose landmarks and draws a Bauhaus-style figurine from discs, hoops, blocks, cylinders, and wedges, then uses a deterministic T-pose whenever no Holistic stream or completed frame is available. The MediaPipe · Blobatar p5 example uses the same pose.nose feature to move a cute blob and falls back to the mouse so it remains runnable without camera permissions.",
    examples: [
      "const body = __.streams.get(\"Holistic\");",
      "const finger = body.feature(\"left_hand.index_finger_tip\", { space: \"scene\" });",
      "const nose = body.feature(\"pose.nose\", { space: \"normalized\" });",
    ],
  },
  {
    id: "script-strudel",
    title: "Strudel quick reference",
    keywords: "strudel quick reference livecode pattern mini notation repl scheduler transport params voices",
    body: "Strudel nodes schedule pattern voices locally while sharing Underscores transport and Mixer routing. Use one $: statement per labelled voice, Mini Notation inside strings or backticks, and __.params for authored controls. Linked is the default; Free gives the node its own clock.",
    examples: [
      "$: note(\"<c e g>\").s(\"piano\")",
      ".color(pure(__.params.tint))",
    ],
  },
  {
    id: "script-manim",
    title: "Manim quick reference",
    keywords: "manim quick reference livecode animation scene cue create transform mathtex transport params",
    body: "Manim nodes run a scene with manim-web's public API plus scene, cue(), MANIM, and __. Use async scene.play calls for animation and optional cue pauses for teaching. Linked follows transport; Free uses the node scheduler.",
    examples: [
      "const shape = new Circle();",
      "await scene.play(new Create(shape));",
    ],
  },
  {
    id: "script-three",
    title: "Three.js quick reference",
    keywords: "three threejs webgl 3d scene camera controls blender option alt orbit pan zoom autofit frame wasd mediapipe holistic unicursal schlemmer costume ribbon renderer mesh geometry material unit cube torus knot orbiting spheres parameter dancing lights energy tick dispose livecode transport params obj zip archive mtl textures walt head",
    body: "Three.js nodes are independent bundled 3D Livecode scenes, not a Manim backend. `/live three` opens a blank source document; the Example menu provides Unit cube, Lit torus knot, Orbiting spheres, Parameter dancing lights, glTF model viewer, Animated glTF blendshape, Walt Head OBJ, MediaPipe Unicursal ribbon (3D), and MediaPipe Schlemmer costume (3D) starters. The two MediaPipe sources read named Holistic landmarks through __.streams and keep deterministic fallbacks until a frame is available. Source receives THREE, scene, camera, renderer, tick(callback), onDispose(callback), loadModel(url, options?), and __. `loadModel` is an allow-listed loader for OBJ, glTF/GLB, USD/USDZ, and ZIP archives containing an OBJ; ZIP models select a bounded in-memory OBJ entry and resolve companion MTL/textures when present. It returns `{ scene, animations, format }`, so an authored node can create an AnimationMixer and apply morphTargetInfluences without importing a loader or touching the DOM. Build geometry once, add it to scene, and animate with tick. Loaded model roots are automatically centered and framed from their bounds when the source leaves the default camera untouched; Option-Home restores that fitted view, while authored camera positioning opts out. Blender-style controls use Option-drag to orbit, Shift+Option-drag to pan, Ctrl+Option-drag to zoom, two-finger drag to orbit, Shift+two-finger drag to pan, and Ctrl+two-finger drag to zoom. When the patch is focused, W/S move forward/back relative to the current camera, A/D strafe, Q/E move vertically, Shift increases movement speed, and arrow keys orbit. Camera state is local runtime state. Linked follows Score transport; Free uses the node clock. Use onDispose for listeners or resources that are not attached to the scene graph. For local files, GLB is the most portable single-file choice; a local .gltf may need its companion .bin and textures available at resolvable URLs.",
    examples: [
      "const cube = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshNormalMaterial());\nscene.add(cube);",
      "tick(({ delta }) => { cube.rotation.y += delta; });",
      "// @param energy = 1.6 (0.4..3 step:0.1)\nconst light = new THREE.PointLight(0x8bd5ff, __.params.energy);\nscene.add(light);",
      "const asset = await loadModel(\"https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/AnimatedMorphCube/glTF-Binary/AnimatedMorphCube.glb\");\nscene.add(asset.scene);\nconst mixer = new THREE.AnimationMixer(asset.scene);\nif (asset.animations[0]) mixer.clipAction(asset.animations[0]).play();\ntick(({ delta }) => mixer.update(delta));",
      "const body = __.streams.list().find(stream => stream.kind === \"holistic\");\nconst nose = body?.feature(\"pose.nose\", { space: \"normalized\" });",
    ],
  },
  {
    id: "media-3d-models",
    title: "3D model inputs",
    keywords: "3d model obj gltf glb usd usdz zip archive mtl textures media input drag drop model viewer animation mixer blendshape morph target preview",
    body: "Drop an OBJ, GLB/glTF, USD/USDZ, or ZIP archive containing an OBJ onto the canvas, or choose it from the Media panel's source picker. The file is stored in this browser's session catalog and becomes a normal Media source; drag the source icon onto the canvas to create a model preview. Canvas model previews are interactive by default: click the model to focus it, then use Option-drag to orbit, Shift-Option-drag to pan, Ctrl-Option-drag to zoom, or the matching two-finger trackpad gestures; W/S/A/D/Q/E and arrow keys work while focused. ZIP archives are unpacked in memory with bounded file and byte limits; scene.obj, model.obj, bunny.obj, or the first OBJ is selected, and companion MTL/textures are resolved when present. GLB is the easiest local format because it bundles geometry, materials, textures, and animations. glTF JSON files can reference external .bin and texture files, so a CORS-enabled URL or a complete resolvable file set is required. USD/USDZ is supported when the file is self-contained. Select a model source to choose a glTF animation, play or pause it, set loop and speed, and adjust discovered morph targets (blendshapes); these source controls update every preview using that source. Remote URLs must allow CORS. The Media panel includes the [Khronos glTF Sample Assets](https://github.khronos.org/glTF-Assets/) Damaged Helmet and Animated Morph Cube, CORS-enabled GitHub Utah Teapot and Stanford Bunny OBJ samples, and the [Three.js Walt Head OBJ](https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/models/obj/walt/WaltHead.obj). The legacy `stanford-bunny-zip` example id remains valid, but the bundled starter now uses a standalone CORS-enabled OBJ; dropped ZIP archives are still supported. `USD` is decoded with Three.js's bundled USDLoader; material and feature support depends on the source file.",
    examples: [
      "/model example=animated-morph-cube",
      "const asset = await loadModel(\"https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb\");",
      "asset.scene.traverse(object => object.morphTargetInfluences?.fill(0.5));",
    ],
  },
  {
    id: "script-markdown",
    title: "Markdown quick reference",
    keywords: "markdown quick reference livecode document headings lists code katex output code overlay",
    body: "Markdown nodes are deterministic local documents. Use normal Markdown headings, lists, code, and emphasis with inline or display KaTeX math. Output, Code, Code Overlay, and Code/Output views change presentation without changing the source.",
    examples: ["# A small patch\n\nUse **Markdown** and $x^2$ together."],
  },
  {
    id: "script-latex",
    title: "LaTeX quick reference",
    keywords: "latex quick reference livecode tex math typesetting katex output code",
    body: "LaTeX nodes provide deterministic local typesetting. Use inline $...$ or \\( ... \\), and display $$...$$ or \\[ ... \\]. Invalid math reports a local error while preserving the editable source.",
    examples: ["\\[ \\int_0^1 x^2 \\, dx = \\frac{1}{3} \\]"],
  },
  {
    id: "script-html",
    title: "HTML quick reference",
    keywords: "html quick reference livecode iframe sandbox css javascript window post onmessage output code",
    body: "HTML nodes run complete HTML, CSS, and scripts inside an isolated opaque-origin iframe. The token-scoped window.__.post/onMessage bridge is available for deliberate messages; parent DOM access, top navigation, and ambient privileges are blocked.",
    examples: ["<button onclick=\"window.__.post('clicked')\">Try it</button>"],
  },
  {
    id: "script-tixy",
    title: "Tixy quick reference",
    keywords: "tixy quick reference livecode expression grid sin cos t i x y params colors transport",
    body: "Tixy evaluates one compact JavaScript expression as (t, i, x, y) over a configurable dot grid. Add @param declarations for grid size and palettes, and use __.transport, __.pointer, __.events, and __.api for Underscores integration.",
    examples: ["sin(t + x / 4) * cos(t + y / 4)"],
  },
  {
    id: "panel-outliner",
    title: "Outliner",
    keywords: "outliner scene objects labels filter native excalidraw code score physics visibility lock delete selection",
    body: "Outliner is the compact inventory of the current patch. Search by label or id, switch filters for native, code, Score, and Physics objects, then select, hide, lock, or delete an object without changing its authored data. Unnamed native Excalidraw objects get stable type/id labels such as stroke_ab12; double-click a row label to replace the generated label with an authored name.",
  },
  {
    id: "panel-playlist",
    title: "Playlist",
    keywords: "playlist anchors cues triggers duration loop play pause next previous",
    body: "Playlist sequences cues and registered commands into a repeatable presentation. Add anchors, choose a trigger, set each duration, and use Play, Next, Previous, or Loop to rehearse the sequence.",
  },
  {
    id: "panel-properties",
    title: "Properties",
    keywords: "properties inspector selected object geometry style transform metadata",
    body: "Properties inspects the current selection. Edit geometry, style, transform, object metadata, and system-specific fields while keeping changes in the normal History and collaboration paths.",
  },
  {
    id: "panel-score",
    title: "Score",
    keywords: "score iannix curves cursors triggers roles timeline midi",
    body: "Score is the time-based curve, cursor, and trigger system. Use the Score panel to author roles and scripts, then let Timeline transport and mappings turn motion into events.",
  },
  {
    id: "panel-script",
    title: "Script",
    keywords: "script editor livecode p5 glsl orca strudel tixy markdown html svg code",
    body: "Script hosts the selected node's source and runtime settings. Pick a script type, edit source, inspect parameters and diagnostics, then compile or run through the node's registered lifecycle.",
  },
  {
    id: "panel-grid",
    title: "Grid",
    keywords: "grid snapping quantize spacing time units selection",
    body: "Grid controls visual snapping and time quantization. Adjust global spacing, toggle selection filtering, and quantize selected objects or timing without changing unrelated scene elements.",
  },
  {
    id: "panel-physics",
    title: "Physics",
    keywords: "physics bodies colliders constraints mappings play reset gravity rapier",
    body: "Physics authors worlds, bodies, colliders, constraints, populations, and collision mappings. Use Play, Reset, and transport sync to inspect runtime motion; use Info for formula details.",
  },
  {
    id: "panel-brush",
    title: "Brush",
    keywords: "brush modifiers channels stroke geometry tracks points javascript",
    body: "Brush applies reusable modifiers to strokes and tracks. Create a channel, choose its source and gate, preview mapped points, and apply or bake the result when the geometry is ready.",
  },
  {
    id: "panel-synth",
    title: "Synth",
    keywords: "synth expressive audio midi voice enable sound programs",
    body: "Synth routes expressive values to internal voices or MIDI destinations. Enable audio with a deliberate gesture, select a program, and keep routing changes inspectable in the patch.",
  },
  {
    id: "panel-media",
    title: "Media",
    keywords: "media camera video audio file source input capture record clip",
    body: "Media manages camera, video, audio, and imported sources. Select a source to preview it, connect it to an actor or processor, and use capture tools when you need a durable clip.",
  },
  {
    id: "panel-inputs",
    title: "Inputs",
    keywords: "inputs signals adapters midi osc events stream",
    body: "Inputs is the bridge for external signals and adapters. Register a source, inspect its latest values or events, and route those values to mappings, Brush channels, or scripts.",
  },
  {
    id: "panel-holistic",
    title: "MediaPipe Holistic",
    keywords: "mediapipe holistic pose hands face landmarks camera tracking",
    body: "Holistic turns a selected media source into semantic face, hand, and pose features. Choose display layers and confidence settings, then consume the normalized landmarks through actors or mappings.",
  },
  {
    id: "panel-mapping",
    title: "Media Mapping",
    keywords: "media mapping actors landmarks bindings signals target",
    body: "Media Mapping connects media features to canvas actors and downstream targets. Add a binding, set its gate and smoothing, and inspect the mapped value before arming it.",
  },
  {
    id: "panel-multiplayer",
    title: "Multiplayer",
    keywords: "multiplayer collaboration room peers share link identity",
    body: "Multiplayer shares authored patch state while keeping each person's camera, selection, and runtime playback local. Create or join a room, verify the peer list, and copy a room link when ready.",
  },
  {
    id: "panel-assistant",
    title: "AI Assistant",
    keywords: "assistant chat ai prompt commands webmcp models ollama",
    body: "AI Assistant can explain the current patch and call the same allowlisted command registry exposed by the palette and WebMCP. Inspect the active model and keep sensitive or destructive actions explicit.",
  },
  {
    id: "panel-history",
    title: "History",
    keywords: "history recording playback session baseline macro walkthrough",
    body: "History records command and presentation sessions with recoverable baselines. Enable Canvas / performance to retain pointer, mouse, pen, touch, wheel, click, or laser motion on the canvas and interactive performance surfaces. Enable UI events separately when a tutorial should retain panel, menu, editor, and settings interactions; keep it off for a clean rehearsal while you tweak the interface. Adjacent UI events from the same pointer family are grouped into one readable clip until another action or event family appears. Gestures are sampled into bounded input actions and playback shows a glowing virtual cursor arrow, cursor ring, or laser path; the Virtual cursor toggle controls that visual layer. Pause, seek, replay, export, or turn a recording into a draft Walkthrough with the input cues preserved for editing.",
  },
  {
    id: "panel-walkthrough",
    title: "Walkthrough",
    keywords: "walkthrough guided tour narration cursor hint retry do it continue pace",
    body: "Walkthrough runs visible automation with a glowing cursor, narration, learner prompts, assertions, and Keep or Restore recovery. Choose a pace or instant mode, then pause or stop at any time.",
  },
  {
    id: "panel-settings",
    title: "Settings",
    keywords: "settings theme colors font shortcuts documentation autocomplete audio",
    body: "Settings contains interface, theme, editor, audio, transport, and documentation preferences. Changes use the active theme tokens and persist locally when they are personal presentation choices.",
  },
  {
    id: "panel-timeline",
    title: "Timeline",
    keywords: "timeline transport play pause seek tempo beats timecode frames loop clips selection block shift",
    body: "Timeline is the shared transport for frame, timecode, and beat-based work. Play, pause, seek, set tempo and meter, mark loops, and follow linked Livecode or walkthrough steps. Shift-click clips to select a contiguous range, Command/Ctrl-click to toggle individual clips, or drag across a lane area to make a block selection; selecting multiple clips also selects their canvas objects. Expanded takes show clips only in their object lanes, so the aggregate take row does not duplicate them.",
  },
  {
    id: "panel-mixer",
    title: "Mixer",
    keywords: "mixer tracks instruments destinations gain mute solo midi audio",
    body: "Mixer organizes instrument tracks and destinations. Add a track, choose its instrument and output, then use mute, solo, and level controls while keeping source programs separate.",
  },
  {
    id: "panel-info",
    title: "Info",
    keywords: "info contextual hover focus quick reference documentation",
    body: "Info is the lightweight contextual reference. Hover or focus a control to see its summary, syntax, or current status, then follow Open in Documentation for the longer page.",
  },
  {
    id: "panel-console",
    title: "Console",
    keywords: "console events logs diagnostics performance fps poll export clear",
    body: "Console shows live events, diagnostics, and performance without adding them to the patch. Filter event types, inspect recent entries, and export logs when diagnosing a system.",
  },
  {
    id: "panel-documentation",
    title: "Documentation",
    keywords: "documentation help table contents search pages patches slash docs",
    body: "Documentation is the searchable learning library for Underscores. Browse nested reference sections, open patch-based lessons, change reading size, or use /docs search <term> and /docs open <id>.",
  },
]);
