export const HELP_TOPICS = Object.freeze([
  {
    id: "start-underscores",
    title: "What Underscores is",
    keywords: "getting started introduction overview welcome first canvas patch drawing code sound motion time performance teaching exploration research",
    body: "Underscores is an infinite creative computational canvas for performance, teaching, exploration, and research. Drawing, code, sound, motion, physics, collaboration, and time share one document instead of living in separate tools. That document is called a patch.\n\nFour ideas carry most of the system. Everything visible is an ordinary canvas object you can select, move, group, and delete. A program is a Livecode node: one canvas object whose contents are running source. Physics is a relationship graph laid over objects you already drew, not a separate simulation window. Timeline supplies one shared clock, so drawings, programs, media, and sound can agree about when things happen.\n\nA patch saves as name.__.json, an Excalidraw-compatible file with an Underscores envelope. The canvas stays quiet: controls live in dockable panels you open when you need them, and every action is a registered command that the palette, the assistant, History, Playlist, and guided walkthroughs all share.",
  },
  {
    id: "start-first-session",
    title: "Your first session",
    keywords: "getting started first steps begin new tutorial quickstart draw livecode p5 play transport welcome walkthrough try",
    body: "Take the guided tour first: run /welcome, or press Getting started at the top of Documentation. It walks through the palette, the core panels, a p5 node, a shader, sound, and a small physics score, and when you stop it offers to restore the patch you began with.\n\nIf you would rather drive, this is the shortest useful path.\n\n1. Draw. Press P for free draw and make a few marks, press V to return to selection, then Home to frame everything.\n\n2. Find things. Open the command palette with Command/Ctrl+/ and type what you want. Every panel also has a slash name: /outliner, /script, /physics, /transport, /docs.\n\n3. Add a program. Run /live p5 to create a Livecode node. Press Enter with it selected to edit on the canvas, or open /script to edit in a panel. Command/Ctrl+Enter runs it.\n\n4. Add time. Open /transport and press Space. Switch a node's clock from Free to Linked and it follows the transport instead of its own timer.\n\n5. Add physics. Select a drawing, Shift-right-click, choose Make Physics Body, then press Play in /physics.\n\n6. Keep it. Run /save to download the patch as .__.json. Nothing is uploaded; the file is yours.",
  },
  {
    id: "start-canvas",
    title: "Canvas basics",
    keywords: "getting started canvas draw select tools pen line hand pan zoom frame home selection group duplicate excalidraw navigate",
    body: "Underscores draws with Excalidraw, so ordinary canvas habits carry over. V selects, P draws freehand, L draws lines and paths, and H pans. Scroll to pan and pinch or Command/Ctrl+scroll to zoom.\n\nSelection follows the familiar defaults. Click selects one object, Command/Ctrl-click toggles it in or out of the selection, and Escape or a click on empty canvas clears. Command-click selects a rectangular, framed, or Underscores-hosted object by its interior, and repeating Command-Shift-click at one point cycles overlapping objects by depth. Option-drag copies.\n\nHome frames every object; Shift+Home frames the current selection. Command/Ctrl+G groups and Command/Ctrl+Shift+G ungroups. The bracket keys change stroke width, and Command/Ctrl with the bracket keys reorders depth.\n\nWhen the canvas gets crowded, open /outliner. It lists every object with search and filters for native, code, Score, and Physics objects, and lets you select, hide, lock, or rename without touching authored data.",
  },
  {
    id: "start-panels",
    title: "Panels and docks",
    keywords: "getting started panels dock docking float collapse layout sidebar bottom left right workspace slash open close resize",
    body: "Underscores keeps the canvas uncluttered and moves controls into panels. Open one from the command palette or by typing its slash name: /outliner, /properties, /script, /physics, /transport, /synth, /media, /inputs, /history, /walkthrough, /mixer, /info, /console, /docs, /settings, and the rest.\n\nMost panels dock to the left or right, or float. Timeline, Mixer, Info, Console, and Documentation can also dock to the bottom, where they share one tab group. Drag a panel by its header to move it between docks; drag its edge handle to resize; click the handle line to collapse.\n\nCommand/Ctrl+B collapses the left dock, Command/Ctrl+Option+B the right, and Command/Ctrl+Shift+B the bottom. Ctrl+Alt+Shift+D resets the workspace to defaults if a layout gets away from you.\n\nPanels are views on one patch, not separate documents. Two panels showing the same Livecode source are two views of one source, never competing drafts. Panel layout is presentation state: it travels with a walkthrough or a saved workspace without being baked into the artwork.",
  },
  {
    id: "start-commands",
    title: "Commands and the palette",
    keywords: "getting started command palette slash commands search actions contextual prompt keyboard registry assistant automation",
    body: "Command/Ctrl+/ opens the command palette. Type a fragment of a command name, an alias, or a slash form and press Enter. The palette is the discovery surface: if an action exists, it is listed there.\n\nSlash commands are the shorthand. Panels use their own name (/physics, /transport), Livecode uses /live plus a kind (/live p5, /live shader, /live strudel), and file actions use /save, /open, /share scene, /export png, and /export fragment.\n\nOption/Alt+Shift+- opens the compact contextual command field without dimming the canvas. It passes the current selection as context, so short property edits go straight through: node opacity 65, blend screen, layer underlay, clock linked, x 240, locked true. Open-ended requests fall through to the assistant with the selection preserved.\n\nOne registry backs all of it. The palette, keyboard shortcuts, the assistant, WebMCP, Playlist triggers, History recordings, and guided walkthroughs call the same command IDs, which is why a recorded session can be replayed and a walkthrough can teach the interface without brittle screen coordinates. Use window.__.commands.list() to read the public contract.",
  },
  {
    id: "start-keyboard",
    title: "Essential keyboard shortcuts",
    keywords: "getting started keyboard shortcuts keys bindings defaults rebind hotkeys space enter escape shortcuts panel",
    body: "Every binding below is a default and every one is rebindable in the Shortcuts panel. Mod means Command on macOS and Ctrl elsewhere.\n\nCanvas: V select, P free draw, L line, H hand, Home frame all, Shift+Home frame selection, Mod+G group, Mod+Shift+G ungroup, Mod+[ and Mod+] change depth.\n\nWorkspace: Mod+/ command palette, Alt+Shift+- contextual command, Mod+, Settings, Mod+B / Mod+Alt+B / Mod+Shift+B collapse the left, right, and bottom docks, Ctrl+Alt+T Timeline, Ctrl+Alt+B Script, Ctrl+Alt+G Grid, Ctrl+Alt+A Assistant, Ctrl+Alt+P Physics toolbar, Alt+Shift+D light/dark, Mod+Ctrl+P presentation mode.\n\nTransport: Space plays and pauses, Shift+Left and Shift+Right jump to the timeline or loop start and end, and Ctrl+Shift+Space is the rehearsal reset toggle that returns to zero and starts or stops from there.\n\nLivecode: Enter edits the selected node on the canvas, Mod+Enter runs or evaluates, Mod+. stops the node under the pointer, Mod+Shift+Enter cycles code, output, and split views, and Mod+Shift+= / Mod+Shift+- change the editor font size.\n\nRecording: Mod+Alt+R toggles History session recording, Alt+Shift+R arms Arrangement recording, Alt+Shift+S switches rolling and step modes, and Alt+Left / Alt+Right move the step playhead.",
  },
  {
    id: "start-patches",
    title: "Saving, sharing, and patches",
    keywords: "getting started save open export import patch fragment help json excalidraw share link png svg selection portable file",
    body: "A patch is one file. /save downloads the current document as name.__.json; naming the file with .excalidraw or .md exports those compatibility formats instead. /open imports a patch or an Excalidraw scene back onto the canvas.\n\nVersioned patch metadata distinguishes three uses of the same envelope. A project is a complete patch with its authored Underscores state. A fragment is a selection plus the authored dependencies it needs, exported with /export fragment and re-importable as many times as you like, since import assigns fresh object and dependency IDs. A help patch is an explanatory patch that can also carry snippets and walkthroughs.\n\n/share scene copies a compressed URL fragment that reopens the current scene. Local media stays metadata-only in that link and may need relinking. The static app can also open a published scene through a ?scene= query parameter pointing at a raw Excalidraw JSON or a Markdown file containing a fenced JSON block.\n\nFor images, /export png and /export svg write the board, with variants for theme background and transparency. Live p5 frames are included in PNG export where the renderer can supply them.",
  },
  {
    id: "start-teaching",
    title: "Teaching and performing",
    keywords: "getting started teaching classroom students demo performance presentation walkthrough history playlist recording screencast lesson course",
    body: "Underscores is built for showing work, not only making it. Presentation mode (Mod+Ctrl+P) hides authoring chrome, the physics toolbar, and the FPS overlay, and restores them on exit; Livecode nodes and shader overlays stay live throughout.\n\nGuided walkthroughs are the teaching format. A walkthrough is an authored document of steps with narration, semantic focus targets, and registered command cues. It can wait for the learner, wait for an assertion about the patch, or advance on its own, and it captures a baseline first so a class can be reset. Open /walkthrough to browse, run, or author them; /docs lists the bundled ones under Help patches.\n\nHistory (/history) records a session as commands and scene changes rather than video, so a take can be replayed deterministically and converted into a walkthrough draft. Playlist (/playlist) sequences cues and commands for a rehearsed presentation. The screencast input overlay (Mod+Alt+I) shows keys and pointer actions on screen while you demonstrate.\n\nFor classroom distribution, npm run build:students produces a single-file public-safe artifact that omits the Strudel runtime and Monaspace fonts; npm run deploy:students publishes it.",
  },
  {
    id: "workspace-interface",
    title: "Workspace interface",
    keywords: "info panel documentation command palette sidebar bottom bar timeline outliner script assistant multiplayer properties settings canvas panels dock",
    body: "Underscores keeps the canvas quiet and moves controls into dockable panels. Use the command palette (Command/Ctrl+/) to find actions, then open Outliner, Script, Physics, Timeline, Assistant, Multiplayer, Properties, Settings, Info, or Documentation as needed. Panels can be moved, resized, collapsed, or restored from their edge handles.\n\nThe workspace is deliberately dense and quiet: a single vertical parameter column in side panels, collapsible sections instead of nested cards, one control height throughout, and restrained translucent fills for state rather than borders or shadows. Bottom-docked Timeline, Mixer, Info, and Console share one tab group and one resize edge.\n\nCommand/Ctrl+B, Command/Ctrl+Option+B, and Command/Ctrl+Shift+B collapse the left, right, and bottom docks. Ctrl+Alt+Shift+D resets the workspace to defaults.\n\nIf this is your first session, read What Underscores is and Your first session under Getting started, or run /welcome.",
  },
  {
    id: "physics-overview",
    title: "Physics overview",
    keywords: "physics overview getting started rapier world system relationship graph body canvas first make body simulate gravity begin",
    body: "Physics in Underscores is a relationship graph laid over objects you already drew. There is no separate simulation document: you select a drawing, give it a body role, and it starts moving while remaining a selectable, copyable, deletable canvas object.\n\nThe fastest way in: draw something, select it, Shift-right-click and choose Make Physics Body (or run /make body). Underscores creates a default World system if the scene has none, infers a collider and material from the shape, attaches a dynamic body, and opens the Physics inspector. Press Play and watch it fall.\n\nOpen the panel with /physics or /relations. It is an inspector and a transport, not a node editor. World holds gravity, viscosity, pixels per metre, and sim speed. Systems lists the worlds in the patch and holds the debug overlay. Bodies, Constraints, and Mappings list what you have authored. The compact floating Physics toolbar (Ctrl+Alt+P, or /physicstoolbar) is the fast authoring surface for Weld, Axle, Spring, and Rope.\n\nGravity is authored in metres per second squared and defaults to 0, -9.8. Because canvas Y grows downward, that conventional negative world-Y reads as falling down the page. Pixels per metre converts world units into canvas coordinates. Sim speed scales elapsed simulation time while the solver keeps its fixed 60 Hz cadence.\n\nAuthored body settings live with the object at customData.physics. Solver handles, live poses, collision queues, and grab joints are runtime-only and never serialize.",
    examples: [
      "/make body",
      "/make rope",
      "/physics",
    ],
  },
  {
    id: "physics-bodies",
    title: "Bodies, colliders, and materials",
    keywords: "physics body dynamic kinematic static sensor collider convex hull path chain bounding box ellipse friction bounce restitution density damping mass collision skin ccd tags shared multi selection",
    body: "A body has exactly one role. Dynamic bodies are moved by forces and contacts. Kinematic bodies move where you put them and push others without being pushed. Static bodies never move. Sensors report overlap without producing contact response. A body may participate in any number of constraints regardless of its role.\n\nThe collider is inferred from the shape and can be overridden in Physics Role. Closed, near-round freehand strokes infer solid circles; other closed strokes infer convex colliders. Path bodies choose between Bounding box, Bounding ellipse, Convex hull, and Path chain. A Path chain is a compound run of rounded solid segments usable for both fixed walls and moving bodies; its physical width follows the canvas stroke width, and overlapping round endcaps keep sharp turns watertight against small fast bodies.\n\nMaterials are friction, bounce, density, and damping, and they are what make a collision sound and feel different. Collision skin is an invisible per-object contact margin in scene pixels; the two skins add together, so it leaves a small visual gap while making fine, fast interactions stable. Keep it small, often 0.5 to 2 px. It is separate from Path chain thickness. Dynamic bodies run with continuous collision detection enabled, so fast objects are swept against their colliders rather than only tested at their endpoints.\n\nSelect several physics objects at once and Properties adds a Shared physics group. Mixed values read as Mixed until you author them; changing a shared field applies to every selected body in one update. This covers body type, enabled and sensor state, tags, collider, friction, bounce, density, damping, collision skin, and layer membership. Objects without a physics role are left untouched.\n\nTags are comma-separated labels on a body. Mappings and actuators filter by them, so tagging a group of bodies is usually easier than naming each one.",
  },
  {
    id: "physics-constraints",
    title: "Constraints: weld, axle, spring, rope",
    keywords: "physics constraint weld axle pin revolute hinge spring rope joint pivot endpoint motor limits fixate rig articulate link length thickness self collision",
    body: "Constraints are authored canvas objects too, not hidden solver handles. Draw the thing, turn it into a constraint, and it stays selectable and editable with its configuration at customData.physics.\n\nWeld and Axle turn selected objects into pivot constraints. The pivot centre is tested against the bodies beneath it: one overlapping body attaches to World, two overlapping bodies join at that point, and no overlap leaves the pivot detached for later endpoint assignment. A Weld may deliberately use one body plus None so an image or costume piece follows that body's local anchor without being pinned to a synthetic world body. An Axle rotates freely through 360 degrees by default; opt into angular limits only when you need them. For a new one-body Axle whose marker contains the start or end of a line, arrow, or freehand body, authoring snaps the marker and its local anchor to that visible endpoint, which avoids an invisible nearby pin that makes the visible tip orbit strangely. Reassign an older Axle to opt into that correction.\n\nSpring uses the selected path's rendered start and end, and exposes rest length, stiffness, and damping.\n\nRope is not a special solver entity. It samples the authored line, arrow, freehand path, Bezier curve, or spline uniformly by arc length into a bounded set of short capsule links joined by revolute joints inside the worker. The generated links never become canvas objects and never serialize individually; the single authored path redraws from their solved endpoints. Link length trades curve fidelity for solver cost and the 96-link cap keeps a dense stroke from producing an unbounded simulation. Thickness sets the physical rope diameter without changing the source stroke. Self collisions is off by default. A rope's own endpoints stay None: tether it by authoring an Axle or Weld pivot over any of its control points.\n\nEdit a named constraint in the Physics panel's Constraints section or in the pivot object's Physics role. Pin, Revolute, and Weld remain compatible vocabulary for existing scenes; the older fixate kind displays as Weld.",
  },
  {
    id: "physics-actuators",
    title: "Actuators: attractor, thruster, motor",
    keywords: "physics actuator attractor repel force radius falloff thruster direction impulse motor axle torque speed drive tags",
    body: "Actuators supply force without you scripting a loop, and like constraints they are authored canvas objects whose settings live with the object.\n\nAn Attractor uses its visual centre as a radial force origin. It attracts or repels dynamic bodies inside its radius with a strength, a falloff, and optional comma-separated target tags, so one attractor can address a tagged subset of a world. The attractor is not itself a collision body unless you separately give it a body role.\n\nA Thruster uses any two-ended canvas object. Its rendered start must overlap a dynamic body and its rendered end gives the force direction. Both are converted to body-local coordinates, so the visible line follows the driven body as it rotates. A thruster pointing only at static bodies is rejected during authoring rather than silently doing nothing.\n\nAn Axle can enable a motor. Motor speed is authored in degrees per second and torque caps how hard the solver corrects toward that speed. Motors apply only to axle-style hinges and are independent of optional angle limits.\n\nAll three update inside the fixed physics step and never enter the render loop. Turn on the debug overlay's force vectors to see what they are actually doing.",
  },
  {
    id: "physics-layers",
    title: "Collision layers",
    keywords: "physics collision layers matrix groups mask belongs to membership pairs rope spool non colliding migrate legacy",
    body: "Collision layers answer two different questions, and keeping them apart is the trick. The matrix under Physics → Collision layers answers which layers collide with which. The Belongs to layers checkboxes on a body or rope answer which layers that object contributes to.\n\nA world holds a stack of up to 15 named layers and a symmetric, editable contact table. A new world starts with one Default layer and every pair enabled, which is ordinary all-to-all collision. A multi-selection applies a chosen membership set to every selected body at once.\n\nA spool setup shows the pattern: assign the rope to ropes, assign the spool body to spool, enable ropes × spool, and disable ropes × ropes if the rope should never touch itself. One body can belong to several layers when it needs to interact with more than one group. An explicitly empty membership is valid and makes a body non-colliding without disabling its joints or queries.\n\nThe final internal bit is reserved for generated rope links, so rope self-contact never consumes an authored layer. Bodies from older scenes keep their raw collision group and mask until you assign them to the named stack, so migration never silently changes an existing simulation.",
  },
  {
    id: "physics-pose",
    title: "Posing, reset, and apply",
    keywords: "physics pose live pose reset apply current paused edits author reset keep baseline drag grab rig ik backslash staging",
    body: "Three separate ideas control what the simulation returns to, and mixing them up is the most common source of confusion.\n\nReset restores the authored baseline pose. Apply current pose commits the running transforms and deformable geometry as one authored history change, making the current arrangement the new baseline. Paused edits decides what an ordinary canvas transform means while a world is paused: Author reset pose, the default, updates the physics reset pose and inferred collider as you move, resize, rotate, or edit; Keep reset pose leaves the saved baseline alone so you can stage temporarily.\n\nLive pose is different again. It is a solver-driven manipulation mode: enable it in Physics World or press \\ outside text entry, pause the simulation or set its time scale near zero, then drag either an authored body or an axle or weld pivot. The grab is full strength at pointer speed while the solver runs bounded zero-gravity constraint iterations, so attached bodies propagate like an IK rig without advancing the physics or transport clock. At timeline zero, releasing the grab promotes the solved result to the authored reset pose so rewind returns to it; at any other time the result stays a temporary runtime pose until you Apply.\n\nSelected bodies and pivots keep the normal canvas transform gesture, so a box-selected group drag is never stolen by the runtime grab handler. Start a grab on an unselected body or joint when you want runtime posing. Box-selecting and moving a complete articulated subsystem is an authored transform: the move updates every selected body's reset pose and every selected pivot's position as one operation and keeps World hinges, body-body axles, welds, and their offsets intact.\n\nWhile a world is running you can also drag a body directly to create a temporary grab spring; releasing it returns control to the solver without changing Reset.",
  },
  {
    id: "physics-transport",
    title: "Physics and time",
    keywords: "physics transport clock sync score seek checkpoint deterministic rewind scrub live timeline preview pause step catch up",
    body: "Each physics system uses either an independent realtime clock or the Underscores music transport clock. With transport sync active, either transport controls the other, so pressing Play in the score starts the world too. Transport rewind, including Shift+Left, resets a transport-linked world together with the score; an independent world is unaffected.\n\nThe solver runs at a fixed 60 Hz in a worker that owns its accumulators, deterministic snapshots, transport checkpoints, bounded catch-up, and collision queues. Pause holds the evaluated pose rather than freezing mid-step, and a paused system stops sending pose buffers at all. Seeking a transport-clocked system restores an in-memory deterministic checkpoint and advances fixed steps to the target, which is what makes a physics score repeatable rather than merely plausible.\n\nLive timeline preview is an optional, browser-local Physics World setting and is off by default. When a world follows the transport, it evaluates the playhead during a timeline drag by restoring and replaying checkpoints. Scrub evaluations suppress collision, audio, and command routes, so scrubbing is a visual preview with no side effects. Large seeks are expensive, and deterministic results require authored or recorded timed inputs rather than live external streams.",
  },
  {
    id: "physics-populations",
    title: "Populations and performance",
    keywords: "physics population particles runtime lite instances seeded materialize performance telemetry fps step transfer render dropped events rope cost",
    body: "A population creates many seeded runtime instances from one authored template without putting hundreds of objects in the patch. Runtime-lite members keep only solver identity, pose, collider, tags, and render style, and their transferable pose buffer is painted by a single imperative canvas overlay rather than a render loop per body. Materialize turns a population into individually authored objects in one undoable change when you want to keep them.\n\nThe acceptance workload is the Musical gas example: 250 runtime bodies at a 60 Hz solver step while canvas rendering stays at or above 45 FPS on the target machine. The performance monitor reports physics.step, physics.transfer, physics.render, body count, collision-event rate, dropped events, and route cost. Treat the overlay as cadence telemetry and use a browser performance trace when you need CPU attribution.\n\nRope cost follows sampled solver links, not the number of points in the source drawing. Sampling is uniform by arc length and capped at 96 links, so a 1,200 px dense stroke at a 24 px link length becomes roughly 58 links rather than hundreds of bodies. While Self collisions is off, generated links share a private runtime collision group, which removes rope-internal contact pairs and avoids a quadratic workload. Enabling Self collisions returns the links to their authored layer groups and lets the matrix govern their internal contacts.\n\nThe general levers, in order of effect: fewer dynamic bodies, larger rope link length, self collisions off, disabled layer pairs you do not need, and the debug overlay turned off, since with it off no diagnostic primitives are collected or painted at all.",
  },
  {
    id: "physics-formulas",
    title: "Physics mapping formulas",
    keywords: "formula mapping physics midi pitch velocity cc bend collision expression variables scale major minor pentatonic",
    body: "Formulas are safe expressions, not JavaScript. They support arithmetic, comparisons, &&, ||, !, parentheses, and if, abs, min, max, clamp, round, floor, ceil, pow.\n\nShared values: raw (selected source field), norm (normalized source range), value (mapped output), impulse, speed, x/y (contact point), normalX/normalY, aX/aY/aVx/aVy/aSpeed, bX/bY/bVx/bVy/bSpeed, gravityX/gravityY, worldTime, step, timeScale, simSpeed, pixelsPerMeter. Body material values are available as aMass/bMass, aFriction/bFriction, aBounce/bBounce, and aDensity/bDensity. Each physics object also has Object note, available as aNote/noteA and bNote/noteB.\n\nPitch formulas also receive baseNote. Scale helpers: major(root, degree), minor(root, degree), pentatonic(root, degree), and scale(root, degree, semitone0, ...).",
    examples: [
      "major(baseNote, floor(speed / 12))",
      "clamp(20 + speed * 2, 1, 127)",
      "round(clamp(8192 + normalX * 8191, 0, 16383))",
    ],
  },
  {
    id: "physics-wayang",
    title: "Wayang puppet and mobile",
    keywords: "wayang kulit rod puppet mobile calder miro chime gamelan slendro articulated arm shoulder elbow hinge wire balance centre of mass mediapipe wrist mouse impulse instrument example",
    body: "The Wayang and mobile example puts an articulated rod puppet in front of a hanging mobile and lets the puppet play it. Run /physics demo wayang, or /wayang, and press Play. The guided lesson is Wayang puppet and a Miro mobile in Documentation.\n\nThe puppet is jointed the way a wayang kulit figure is. Its body swings from a single world hinge, its head is welded on, and each arm has two segments joined at a shoulder hinge and an elbow hinge. Two segments is the point: one segment can only sweep an arc, while two can place a hand on a chosen point. The arms are authored already hanging, which keeps the rest pose compact and leaves the composition's right half free.\n\nThe mobile is built the way a Calder mobile is. Every wire is a real body with a hinge at each end, because a bar hung from a single link is free to spin about that one point and the assembly flails instead of swinging. The top bar's hook is derived rather than guessed: the builder takes the centre of mass of everything the bar carries and pivots there, so the mobile balances by construction. Every part carries linear and angular damping, standing in for air and wire friction, so the rig settles into a rest pose a performer can aim at.\n\nCollision filtering uses raw group and mask bits rather than the named layer stack, because an example's graph is merged into whatever world the patch already has and world settings are not part of that merge. Puppet parts therefore pass through each other, both collide with the mobile, and the mobile's shapes clink against each other.\n\nTwo mappings ship with it. Hand strikes mobile listens for a body tagged wayang-hand meeting one tagged mobile-chime; Mobile shapes meet listens for the chimes meeting each other, an octave up and quieter, so one strike sets off a cascade. Pitch reads contact height and impact strength through a five-tone scale inspired by slendro. That is an approximation for a teaching patch, not a tuned gamelan: real slendro is close to equidistant and varies by ensemble.\n\nOnly the nearest chime is inside the arm's reach. The others ring because the mobile swings into itself, which is what the chime-to-chime mapping is for.\n\nPlay it two ways. With the world running, drag a hand into a chime: dragging a running body makes a temporary grab spring, so the arm still obeys its joints and the authored pose is unchanged. For both hands at once, add the MediaPipe · Wayang rod controller p5 node. Its surface maps onto the puppet's reach, driving the near hand from the mouse and both hands from Holistic wrists when a camera is running. It never sets a position: each frame it applies an impulse toward a target through __.api.physics.impulse, so the arms stay under the solver.",
    examples: [
      "/physics demo wayang",
      "__.api.physics.impulse(systemId, bodyId, { x: 120, y: -80 })",
    ],
  },
  {
    id: "physics-marionette",
    title: "Physics marionette case study",
    keywords: "physics marionette paper doll bauhaus schlemmer rig body pin spring axle revolute live pose mouse wind chime collision expressive synth mediapipe t-pose history recording playback walkthrough case study",
    body: "The Marionette case study builds a Bauhaus-inspired paper doll from four ordinary canvas primitives, then layers an articulated rig, collision sound, a second MediaPipe-driven visual rig, and History playback on top of it. Run `/walkthrough start physics-marionette-study-v1` for the seven-stage lesson, or `/physics demo marionette` to jump straight to the finished starter.\n\nThe generated world contains a world pin holding the head, a damped neck spring, and revolute shoulder joints. Read that structure before touching it: the invisible relationships matter as much as the visible costume, and both are inspectable in the Physics panel and in each part's Physics role.\n\nPlay the world and drag an unselected body or joint for a temporary live pose. Reset returns to the authored pose; Apply current pose commits a staged arrangement as the new baseline. A selected object keeps the normal canvas transform gesture, so start a grab on an unselected part when you want runtime posing.\n\nAdd a body-to-body Expressive Synth mapping and contacts behave like small wind chimes. Then keep the physics doll running while a separate MediaPipe · Schlemmer pose p5 node supplies a second rig for comparison; with no completed camera frame the example falls back to a deterministic T-pose, so the lesson works before camera permissions or model assets are ready.\n\nFinally record a short gesture with History, stop the take, and use `/history play`, the playhead, export, or Create walkthrough to review and share it. The full classroom notes live in `notes/examples/physics-marionette.md`.",
    examples: [
      "/walkthrough start physics-marionette-study-v1",
      "const graph = __.api.relations.get();\nconst world = graph.systems.find(system => system.name === \"Marionette\");\nconst bodies = graph.bodies.filter(body => body.systemId === world?.id);\nconst joints = graph.constraints.filter(constraint => constraint.systemId === world?.id);",
      "await __.api.commands.execute(\"physics.mapping.create\", { collisionClass: \"body-body\", target: \"expressive-voice\" });",
      "const holistic = __.streams.list().find(stream => stream.kind === \"holistic\");\nconst nose = holistic?.feature(\"pose.nose\", { space: \"normalized\" });\nconst physics = __.api.physics;",
      "/record start\n/record stop\n/history play",
    ],
  },
  {
    id: "physics-mappings",
    title: "Physics collision mappings",
    keywords: "physics collision mapping source filter transform target midi expressive synth begin hit end stay contact body wall tags object",
    body: "Mappings run Source → Filter → Transform → Target without a React render. Source chooses a system, collision class, contact phase, tags or specific objects, and a numeric field. Filter rejects events by range or boolean formula. Transform maps the surviving value. Target sends MIDI Note, CC, Pitch Bend, or an Expressive Synth voice.\n\nUse hit for one note per impact. Use begin/end with a pair-gate target for notes or voices that persist while a pair is in contact. Stay is opt-in and drives continuous expressive updates while Contact stay events is enabled for the world.",
  },
  {
    id: "physics-debug",
    title: "Physics debug overlay",
    keywords: "physics debug overlay diagnostic collider contacts collisions forces labels bodies springs constraints trails tracer pulses inkwash emitter color toggle",
    body: "The debug overlay is how you see what the solver sees. It draws diagnostic body bounds, actual collider geometry, labels, constraints, contacts, collision pulses, and force vectors in the same canvas and world coordinate system as your authored objects.\n\nIt is diagnostic only. Its data is runtime-only and never serializes or exports, so nothing it draws becomes canvas art. Each category toggles independently and takes a theme-aware CSS color, including named colors, hex, CSS color functions, and `object` to follow the object's own color. Labels prefer the canvas or Outliner name over internal IDs. A one-sided constraint with a deliberate None endpoint still shows its live attachment marker rather than disappearing.\n\nTurn on Colliders first when a shape is not colliding as expected; it is usually the fastest answer. Force vectors are the equivalent for attractors, thrusters, and motors that appear to do nothing.\n\nThe same path draws transient **trails**. A body trail follows its centre of mass, and Axles and Welds can plot their body-A and body-B attachment points independently, so real joint separation appears as two diverging traces. A standalone **Tracer** follows an object point without becoming a physics body. Trail color, opacity, and retained duration are debugging controls only and never touch the authored scene or the solver.\n\nWith the overlay off, no diagnostic primitives are collected or painted at all, so it costs nothing when unused. While it is on, its visible strokes are also published as runtime-only segments to the shader scene bridge, which lets an Inkwash node in Physics debug emitter mode react to collider, constraint, contact, force, and trail drawings without creating any canvas objects.",
  },
  {
    id: "timeline-overview",
    title: "Timeline overview",
    keywords: "timeline transport overview shared time play pause stop seek playhead score clock global rehearsal space bar getting started",
    body: "Timeline is the shared clock. Drawings, Livecode nodes, media, physics worlds, and sound all agree about when things happen because they read the same transport, and anything that does not want to can stay on its own free clock instead.\n\nOpen it with /transport or Ctrl+Alt+T. It docks to the bottom by default, where it shares a tab group with Mixer, Info, and Console, and it stays one compact row.\n\nSpace plays and pauses. Shift+Left and Shift+Right jump to the timeline or loop start and end. Ctrl+Shift+Space is the rehearsal reset toggle: from either state it sets score time to zero and then stops or starts from there, and it keeps working while an editor has focus, which is what makes it useful mid-demonstration.\n\nThe panel carries more than a playhead. Above the ruler sit arrangement lanes for clips and takes; below it are a keyframe lane for object automation and a read-only marker lane showing the steps of an active guided walkthrough. A zoom strip at the bottom sets the visible window.",
    examples: [
      "/transport",
      "transport.seek { \"seconds\": 4 }",
    ],
  },
  {
    id: "timeline-time",
    title: "Frames, timecode, and beats",
    keywords: "timeline time display mode frame timecode beats bbu bar beat sixteenth tempo bpm meter time signature fps rate units convert",
    body: "The same position can be read three ways and you switch between them freely. Frame shows an integer frame count. Timecode shows hours:minutes:seconds:frames. Beats shows bar.beat.sixteenth, so 1.2.0 is the second beat of the first bar.\n\nFrame rate is one of 24, 25, 30, 50, or 60, and it governs both frame display and timecode. Tempo is clamped between 20 and 400 BPM. The meter's numerator and denominator drive bar length and the beat grid.\n\nThe display mode also changes the ruler's subdivisions and what snapping means. In beats mode the minor division is one beat and the major is one bar. In frame mode the minor division is a single frame and the major is one second. In timecode mode the divisions are chosen to keep roughly a dozen readable steps across the visible window.\n\nTime-value fields elsewhere in the application accept the same vocabulary, so an arrangement step size or a clip length can be written in frames, beats, bars, or seconds rather than converted by hand. Timecode and tempo use the regular control font size; their meaning, not oversized type, supplies the emphasis.",
  },
  {
    id: "timeline-navigation",
    title: "Seeking, zooming, and looping",
    keywords: "timeline seek scrub drag playhead zoom window pan fit loop range snap command shift markers keyframes walkthrough",
    body: "Drag the ruler to seek. Hold Command while dragging to snap to major units and Command+Shift to snap to minor ones. Shift-drag across the ruler marks a loop range; drag the loop bar to move it, or either handle to change its start or end.\n\nThe zoom strip under the timeline sets the visible window. Drag it to pan, drag its edges to zoom, Command-click to fit the whole score, and Option-click to fit the loop. Zooming only changes what you are looking at; it never alters timing.\n\nThe keyframe lane shows object automation keys within the visible window, each labelled with its property path and position. The walkthrough marker lane shows the steps of an active guided walkthrough as read-only markers, which is how a transport-linked walkthrough stays legible while it plays.\n\nDragging the playhead itself is a normal seek. Whether a physics world follows depends on its own clock setting and on whether Live timeline preview is enabled for that world.",
  },
  {
    id: "timeline-arrangement",
    title: "Arrangement clips",
    keywords: "timeline arrangement clip take lane schedule object participate global score when appears hold add clip at playhead mute solo",
    body: "Arrangement clips schedule when an authored object participates in the score. They are not a second copy of the object: a clip maps global time onto that object's existing local lifecycle. This page describes Timeline's **Object lanes** mode; see Clip lanes for the user-authored track mode that shares the same transport.\n\nCreating an object's first clip opts it into arrangement scheduling; deleting its last clip returns it to ordinary always-present behavior. Objects with no clips do not consume a timeline row at all, so the lane list stays as short as the piece requires.\n\nAdd clip at playhead opts the current selection in with a sensible default: static objects use Hold, media uses its intrinsic duration when known, gesture objects use their recorded duration, and Livecode defaults to one bar. A Hold clip follows project end without extending it; a fixed clip has an explicit window.\n\nTake rows are collapsed summaries by default. Expand a take and its clips render in the individual object lanes while the aggregate row remains a header, so nothing is drawn twice. Arranged objects that do not belong to a take get standalone lanes. Each take row carries M and S buttons: muting or soloing a take changes evaluation without touching the authored objects underneath.\n\nProject end is the latest fixed clip, score-object or automation end, enabled loop end, or a ten-second minimum, whichever is greatest. Hold clips and History duration do not extend it.",
  },
  {
    id: "timeline-clip-lanes",
    title: "Clip lanes",
    keywords: "timeline clip lanes tracks mode object lanes user authored edit drag history action outliner soundtrack cue command scene midi track mute solo reorder add rename",
    body: "Clip lanes is the second of Timeline's two lane modes, and it answers a different question from the first. **Object lanes** asks when each canvas object participates, so its lanes are derived from the objects themselves. **Clip lanes** asks what happens when, so its tracks belong to you: you name them, order them, and drop material onto them.\n\nSwitch with the two buttons at the left of the timeline. Object lanes is one lane per canvas object; Clip lanes is user-managed tracks. Your choice is remembered locally. Switching to Clip lanes for the first time creates three empty tracks to drop onto.\n\nBuild a track list with the `+` control, rename a track in place, use the move-earlier and move-later controls to reorder, and mute or solo a track to audition without deleting anything. Then fill the tracks: drag a **History action** from the History panel onto a track, or drag an object from **Outliner**, including Livecode nodes, media, and text.\n\nA clip records which kind of thing it points at — a history action, a canvas element, a command, media, or a Livecode node — along with its label and timing. The important consequence is that **clip timing is independent of the source object's layer**. A Livecode node's position in the drawing has nothing to do with which track its clip sits on, so the same node can appear on whichever track makes editorial sense.\n\nWhat a clip does at its start depends on its kind. Livecode and media follow the clip's local playhead, so a node placed on a clip reads clip-local time rather than global score time. History command, scene, and MIDI cues fire once when their clip starts, which is what makes this mode usable as a cue sheet for a performance.\n\nThe selection gestures are the same in both modes: Shift-click for a contiguous range, Command/Ctrl-click to toggle one clip, or drag across a lane for a block selection.\n\nClip-lane tracks and clips are saved with the patch. Arrangement metadata is version 2; a patch written before Clip lanes existed loads as Object lanes with no tracks, which is exactly its previous behavior.",
  },
  {
    id: "timeline-clips",
    title: "Editing clips",
    keywords: "timeline clip edit move trim stretch rate loop delete select shift command block selection snap history transaction offset",
    body: "Select a clip and its canvas object is selected too; selecting an arranged object reveals its lane. Shift-click extends a contiguous range, Command/Ctrl-click toggles individual clips, and dragging across the clip area makes a block selection. A multi-clip selection selects every corresponding canvas object while the last clip clicked stays the active edit target.\n\nDrag a clip body to move it. Drag either edge to trim the active window; a left trim also advances the source offset, so the material inside keeps its relationship to the new edge. Hold Command while dragging for major ruler snapping or Command+Shift for minor. Option-drag an edge to stretch the internal lifecycle by changing playback rate rather than trimming it. Double-click a clip to toggle local lifecycle looping. Delete removes the selected clip, and removing a take removes its child clips so a deleted recording does not reappear during playback.\n\nEvery edit commits once at pointer release as a single scene-history transaction, so an entire drag is one undo. Runtime evaluation is transient and never writes scene JSON per frame.\n\nPlacement lives with the object at customData.underscoresArrangement, while takes, lane order, mute and solo state, recording mode, and step size live in scene metadata. Duplicated clips receive fresh clip and recording IDs, so copying an arrangement never aliases the original.",
  },
  {
    id: "timeline-recording",
    title: "Arrangement recording",
    keywords: "timeline arrangement record rolling step mode arm disarm hold one frame gesture take loop boundary playhead alt shift r",
    body: "Arrangement Record captures performance into clips, and it is independent from History recording. Alt+Shift+R arms and disarms it, Alt+Shift+S switches between Rolling and Step, and Alt+Right and Alt+Left move the step playhead by the configured value.\n\nRolling starts from the current playhead and starts transport playback when necessary. A completed drawing becomes a gesture lifecycle and a clip. Manually started media or Livecode creates a pending clip that is finalized when it stops or the transport stops. Changing record mode affects the next event, not one already in progress.\n\nStep mode keeps the transport paused, which suits building an animation frame by frame or laying out a lecture beat by beat. A completed object defaults to Hold through project end, or you can choose a one-frame window. The step value accepts frames, beats, bars, and seconds through the shared time-value control. Raw gesture timing is retained even when the first presentation is a static Hold or one-frame clip, so you can convert later without having lost the performance.\n\nRecordings that cross a loop boundary become source-continuous linked segments sharing one recording ID, and each loop pass becomes an overlay take. Every sample keeps three clocks: monotonic unwrapped recording time, visible transport time which may wrap, and loop phase with iteration.",
  },
  {
    id: "timeline-lifecycle",
    title: "How clips drive objects",
    keywords: "timeline lifecycle adapter activate seek deactivate static gesture media livecode strudel overlap resume latest started wins evaluate clip",
    body: "Each kind of object exposes the same four operations to the arrangement: an intrinsic duration, activate, seek, and deactivate. What those mean is adapter-specific, and knowing which one applies explains most playback surprises.\n\nStatic objects are gated for display and interaction only. Their authored geometry, opacity, deletion, and lock state in the saved scene are untouched. Gestures render progressive recorded geometry at local clip time and then hold the completed path for the rest of the window; freehand playback reuses the native outline for each revealed prefix, so pressure feel, caps, joins, and corners survive rather than becoming a constant-width polyline. Gesture playback is an overlay: the authored stroke stays the source of truth and the scene JSON is not rewritten every frame. Media maps local time to audio, video, or GIF playback with corrective seeks only on discontinuities. Livecode restarts from local zero on activation and stops at clip end while preserving Keep last frame; p5 and shader nodes receive deterministic local time for playback and scrubbing, while Strudel does not emit retroactive scrub audio.\n\nOverlap resolves by a deterministic latest-started-wins rule with take order as the tie-breaker. When the winning clip ends, an earlier overlapping clip resumes at its transport-derived local time rather than restarting.\n\nA once-through visual lifecycle holds its final state inside a longer window while audio goes silent; Loop repeats the local lifecycle to fill the window instead. Objects with no arrangement metadata keep their previous gesture, media transport-link, and free or linked Livecode behavior.",
  },
  {
    id: "score",
    title: "Score roles",
    keywords: "score iannix curve cursor trigger transport midi role",
    body: "A Score combines curves, cursors, and triggers. Curves provide the path, cursors travel it in score time, and triggers emit messages at positions on a curve. Score roles are independent from physics roles; mappings and scripts can bridge their events when needed.",
  },
  {
    id: "media-streams",
    title: "Media streams and actors",
    keywords: "media stream mediapipe holistic camera actor brush input landmark source catalog clip recorder gif mp4 webm alpha transparent key black green color threshold softness opacity blend layer background overlay underlay audio download frame all loop",
    body: "Media sources stay dormant in the catalog until selected or connected to an enabled scene object. Select one to preview and play it, use Record clip to create GIF, MP4 with source audio, audio-only, or WebM alpha clips, and press Escape to clear selection. Canvas capture can target a frame, rectangle, or the full scene. A Holistic processor stores its source, transform, and display settings without creating one object per landmark. Visual media previews use the same compositor vocabulary as Livecode: Layer places them above or below native objects, Opacity controls the surface, Blend selects a CSS blend mode, and Background chooses transparent, theme, or solid. The source panel exposes these as defaults for new previews. Processed camera/canvas/video output is drawn into an alpha-enabled canvas and published to the media image stream; trusted code can inspect `__.streams.get(\"media:<source-id>\").snapshot().alpha` and request its active `stream()` when a browser capture bridge is available. Native webcam/video elements report `alpha: false` unless keying creates transparent pixels, even when a producer such as SketchCam publishes BGRA alpha upstream; use Key with Black, Green, or Picked color and tune Threshold/Softness when the browser transport flattened it. Use the Media and Inputs panels to create streams, then use actors, Brush channels, or scripts to consume them.",
  },
  {
    id: "livecode-overview",
    title: "Livecode nodes",
    keywords: "livecode node overview what is create live p5 shader glsl strudel orca tixy svg markdown latex html three manim kind canvas program source rectangle customdata",
    body: "A Livecode node is one canvas object whose contents are a running program. The object is an ordinary transparent rectangle: it owns position, rotation, size, selection, history, grouping, depth, and the persisted record at customData.underscoresLivecode. The living surface inside it is supplied by a per-kind adapter rather than by the drawing engine.\n\nThat separation is the whole design. A program is not attached to a special host object and does not take over the document. A node has exactly one source document, and any number of nodes can run side by side without interfering.\n\nCreate one from New Livecode Node, the command palette, livecode.node.create, or /live. Naming the kind goes straight there: /live p5, /live three, /live playcore, /live shader, /live strudel, /live orca, /live tixy, /live svg, /live markdown, /live latex, /live html. A new node starts blank unless you pass an example or source; pick a starting point from the node's Example menu when you want running code immediately.\n\nSelecting a node opens its source in the shared Script panel. Pressing Enter, or clicking its code, edits the same source directly on the canvas. These are two views of one document, never competing drafts, and switching between them never interrupts a running runtime.",
    examples: [
      "/live p5",
      "/live shader",
      "livecode.node.create { \"kind\": \"p5\", \"name\": \"Orbit\", \"running\": true }",
    ],
  },
  {
    id: "livecode-lifecycle",
    title: "Running, stopping, and updating",
    keywords: "livecode run stop start evaluate compile auto-update manual draft keep last frame lifecycle cmd enter ctrl enter error recover",
    body: "Command/Ctrl+Enter is the main gesture. On a stopped node it starts the program; on a manual-update node it evaluates the current draft and starts it if needed. When the pointer is over a node on the canvas, the same chord runs it without focusing the editor, and Command/Ctrl+. stops that hovered node.\n\nAuto-update decides what an edit means. With Auto-update on, every valid edit compiles immediately, which is the default for visual and document kinds. With it off, edits stay authored drafts until you evaluate them explicitly, which is the default for Strudel; the node keeps its last evaluated source and its running surface while you type. The compact toggle sits beside the run control in the Script panel: a circular arrow with a dot means automatic, a return corner with an upward chevron means manual.\n\nAdapters that can compile keep their last working output when a new version fails, whether it came from an auto-update edit or an explicit evaluation. A failed shader edit is reported in the Console's Live status stream while the canvas keeps its last good frame; compiler text never replaces the output.\n\nKeep last frame is on by default for canvas-rendered kinds, so a stopped node holds its final image. Turn it off when a stopped node should disappear instead.",
    examples: [
      "livecode.node.run",
      "livecode.node.stop",
    ],
  },
  {
    id: "livecode-views",
    title: "Code, output, and split views",
    keywords: "livecode view code output preview split overlay glyphs only cycle enter presentation markdown strudel orca surface scroll",
    body: "Every node persists which surface it shows. Code shows the source document. Code overlay keeps the running output underneath the source. Output shows the runtime without source glyphs. Code/output is the explicit split.\n\nCommand/Ctrl+Shift+Enter cycles these views while a node editor has focus. Enter on a selected node opens the authored code view and focuses its canvas editor. On a canvas output, a plain Command/Ctrl-click switches that node to Output; Command+Shift-click stays reserved for the canvas overlap-cycle gesture.\n\nGlyphs only is on by default for Code overlay. The overlay opacity is painted behind non-whitespace runs only, so blank areas stay transparent and the running output shows through the gaps in the code. Turn it off for one continuous code surface.\n\nThree kinds bend these rules deliberately. Strudel has no Code/Output split, because its Output surface is already a read-only editor that keeps synchronized event highlights, markcss styles, and inline visualizers alive after the static glyphs are hidden. Markdown's Output is also its document editor: double-click a rendered block to edit that block's exact source, click another block to move the session, or click below the last block to append. Orca is code and grid only, since its code is its output.",
  },
  {
    id: "livecode-clock",
    title: "Free and linked clocks",
    keywords: "livecode clock free linked transport score time sync tempo quantize launch activation bar beat seek rate stopwatch",
    body: "Each node runs on either its own clock or the shared one. Free uses a node-local timer and keeps running regardless of the transport. Linked follows the score's play, pause, seek, and rate, so several nodes and the music stay in phase. The compact toggle sits beside Auto-update in the Script panel and uses a stopwatch for Free and a square subdivided clock for Linked; Timeline uses the same square-clock symbol.\n\nVisual and document kinds default to Free. Strudel defaults to Linked and follows transport tempo and phase: play, rewind, loop, backward seek while playing, seek while stopped, and BPM changes all re-anchor its cycles to score time. A backward seek hard-resets its scheduler cycle so patterns begin from the new origin rather than keeping an old phase.\n\nA node's transport time is scoped to that node. __.transport.time, and its __.time shortcut, read the node's own clock: global score time for an ordinary linked node, but the node's local clip time when it is playing from a Clip lanes timeline. A sketch written against score time therefore keeps working when you drop it onto a track, and starts from the beginning of its clip rather than wherever the global playhead happens to be.\n\nQuantize linked activation makes launching feel like a clip launcher. When it is enabled, starting or stopping a linked node from its run control waits for the next musical boundary. The control is Q plus an interval selector in the compact transport, and it also lives in Settings under Score & MIDI. Intervals are 1/16, 1/8, 1/4 beat, 1/2 beat, 1 bar, 2 bars, 4 bars, or a custom number of beats. It is shared by all linked nodes and persists with the session.\n\nA newly launched node gets a fresh phase origin at its actual activation, so its first event starts at the beginning of the clip rather than inheriting the transport's current position. Stopping the transport cancels queued starts and stops, and toggling a queued node again cancels its pending change. Free nodes and already-running nodes are unaffected.",
    examples: [
      "clock linked",
      "clock free",
    ],
  },
  {
    id: "livecode-bridge",
    title: "The Underscores bridge (__)",
    keywords: "livecode bridge underscores api __ params transport canvas events streams colors api window global trusted sandbox html token",
    body: "Trusted runtimes receive the application through one reserved binding, __. It is node-local: each program sees its own element, parameters, and lifecycle, and there is no spelled-out alias.\n\nThe usual members are __.transport for the node's transport time and tempo, with __.time as a shortcut for __.transport.time, __.params for declared @param values, __.canvas for querying and creating canvas objects, __.events for the event bus, __.streams for typed media and input streams such as MediaPipe Holistic landmarks, __.colors and live Excalidraw color aliases that resolve on access, and __.api for the registered command surface. Because color references resolve when read, a running node follows a changed palette without recompiling. Transport time is scoped the same way: it reports the node's own clock, which is the local clip time when the node is playing from a Clip lanes track and global score time otherwise.\n\np5, Play Core, Three.js, Strudel, Tixy, and Manim receive this bridge. Tixy also gets it as the fifth argument of its expression and through __.tixy. Sandboxed HTML deliberately does not: it runs in an opaque-origin iframe and receives only a narrow token-scoped window.__ with post and onMessage, and the parent verifies both token and source window before answering.\n\nThe application also publishes its public API as window.__ outside any node. Use window.__.commands.list() to read the command contract rather than calling internal UI handlers.",
    examples: [
      "const t = __.time; // shortcut for __.transport.time",
      "const nose = __.streams.get(\"holistic\").snapshot()?.pose?.nose;",
      "await __.api.commands.execute(\"transport.seek\", { seconds: 2 });",
    ],
  },
  {
    id: "livecode-typography",
    title: "Node typography",
    keywords: "livecode typography font size line height weight tracking ligatures monaspace fira inter serif line numbers fold gutter editor",
    body: "Typography is stored per node and edited in the Script panel, so a presentation node and a working node can look completely different in the same patch. Choose Fira Mono for code, Inter for readable presentation, a system serif, or one of the five Monaspace families: Argon, Krypton, Neon, Radon, and Xenon.\n\nSize, line height, weight, tracking, and the Ligatures toggle are stored with the node. Monaspace enables contextual alternates, standard ligatures, and the stylistic operator sets when Ligatures is on. Fira Mono, Inter, and the Latin Monaspace faces are bundled offline at the supported editor weights.\n\nCommand/Ctrl+Shift+= and Command/Ctrl+Shift+- change the focused editor's font size by one pixel, clamped between 8 and 72. The value is written into that node's typography, so the canvas editor and the Script panel agree. Line numbers and the folding gutter are both available in the panel and both default off for canvas nodes; Ctrl+M then L is CodeMirror's own line-number toggle.\n\nThe global CodeMirror palette still owns syntax colors and editor surfaces. Node typography only changes that node's own source and preview content.",
  },
  {
    id: "livecode-troubleshooting",
    title: "When a node will not run",
    keywords: "livecode troubleshooting error debug blank frame compile runtime console live status p5 error shader transparent background clear scope",
    body: "Check the Console first. Open /console and read the Live status stream: it reports compile failures and runtime failures, with p5 problems appearing as p5 error: messages. Successful output on the canvas remains the authority for whether a repair worked.\n\nA node can compile and still fail during its first draw. In classic p5 sources, keep values you need after a candidate-generation loop in the enclosing function scope rather than declaring them only inside the loop, and give pointer-centered sketches a fallback when an intersection filter rejects every candidate, or the frame goes blank with no compile error. Use p5's built-in dist() directly; even a commented-out function dist(...) can be mistaken for an authored binding by the classic-mode declaration scan.\n\nIf a node looks stuck on an old image, check Auto-update and Keep last frame. A manual-update node keeps its last evaluated source running while you edit, and a failed evaluation leaves the previous valid output in place; both are working as intended, so evaluate explicitly with Command/Ctrl+Enter.\n\nFor a foreground-only frame, call p5 clear() at the start of draw(). background(\"transparent\") and background(0, 0) are not reset operations: they paint an alpha-zero source over the surface and can leave earlier pixels accumulated. Set Background to Transparent on the node so the host surface has a real alpha channel.\n\nIf nothing is audible, sound needs a deliberate gesture. Open /synth and enable audio; browsers will not start Web Audio from automation.",
  },
  {
    id: "script-parameters",
    title: "Script parameters",
    keywords: "parameter params param declaration number range step string text color picker eyedropper boolean bool json object canvas element reference p5 play core livecode brush tixy shader score",
    body: "A `// @param` comment turns a hard-coded value into a control. Declare it once in the source, read it through `__.params.name`, and the Script panel builds the editor for it.\n\nDeclarations accept numbers, strings, CSS colors, booleans, parsed JSON values, and canvas object references. A number keeps its range and step, so it drags and resets like every other numeric control. A color uses the compact in-app picker with a live app and canvas eyedropper preview, and accepts dynamic __ color references so the value follows a changed palette. JSON is edited as a JavaScript value. An object reference resolves through the canvas query API, which is how a sketch can address a specific drawing.\n\nParameters are persisted with the node and travel with the patch, so a lesson can ship a sketch with its controls already set. Changing a parameter does not recompile the program; the running node simply reads the new value on the next frame. For a manual-update node such as Strudel, editing a parameter queues a fresh evaluation at the next safe beat instead.\n\nThe same declaration syntax works across p5, Play Core, Three.js, Tixy, shaders, and Brush sources, which is why examples like Fluid Brush and Inkwash expose `emission` as an ordinary parameter rather than a hidden node setting.",
    examples: [
      "// @param count = 8 (2..40, step: 1)",
      "// @param hue = #78dcff (color)",
      "// @param mirrored = true (boolean)",
      "// @param bounds = [16, 20] (json)",
    ],
  },
  {
    id: "livecode-compositing",
    title: "Livecode compositing",
    keywords: "livecode compositing composition layer underlay overlay blend opacity background transparent theme solid performance gpu fluid brush emission",
    body: "Every visual Livecode node can be composed without flattening its output. Layer places the node above or below native canvas objects; Opacity and Blend are browser-compositor properties; Background controls the host surface while preserving adapter-owned pixels. Defaults remain Above objects, 100%, Normal, and Adapter default, so an untouched node adds no extra blending work.\n\nLarge overlapping translucent or blended surfaces cost GPU fill-rate in proportion to their pixel area. Prefer Normal for nodes that do not need blending, keep full-canvas feedback nodes bounded, and avoid stacking many Retina-sized transparent surfaces. Composition never reads pixels back or writes scene state per frame.\n\nFluid Brush and Inkwash declare // @param emission = true (boolean). Emission lets the chosen scene or physics-debug geometry continuously inject and stir dye or wet pigment. Turn it off in Parameters to keep pointer painting while skipping geometry collection. Older patches with the former node setting remain compatible.",
    examples: [
      "layer underlay",
      "blend screen",
      "node opacity 65",
      "// @param emission = true (boolean)",
    ],
  },
  {
    id: "script-svg",
    title: "SVG quick reference",
    keywords: "svg quick reference path shape transform style viewbox source editor anchor bezier",
    body: "SVG nodes keep their source as editable text while exposing paths and shapes on the canvas. Use viewBox for document coordinates, path d commands for geometry, and currentColor or explicit CSS colors for styling. Command-click a rendered path to edit it; double-click a segment to insert an anchor, and use Properties or Outliner when you need a precise subpath selection.",
    examples: [
      "<svg viewBox=\"0 0 320 180\">",
      "<path d=\"M20 90 C80 20 240 160 300 90\" fill=\"none\" stroke=\"currentColor\" />",
    ],
  },
  {
    id: "script-p5",
    title: "p5 quick reference",
    keywords: "p5 quick reference livecode javascript sketch setup draw createcanvas params transparent frame reset mediapipe blobatar avatar mouse follow pollock splatter action painting gesture",
    body: "p5 sketches run as self-contained Livecode nodes. setup() runs once, draw() runs each frame, and __.element plus __.params connect the sketch to its host and declared controls. __.transport.time (and its __.time shortcut) is the shared score clock, or the local playhead when the node is playing from a Clip lanes timeline. The Example menu includes MediaPipe · Blobatar: a small, theme-aware avatar whose body eases toward pose.nose and falls back to mouseX/mouseY when no Holistic frame is available, and Pollock / Splatter: an editable action-painting study where gesture speed controls paint thickness and every paint/spray control is exposed as a parameter. Change p5 version, transparent-surface, and frame-reset settings in Node settings when a sketch needs a different lifecycle.",
    examples: [
      "function setup() { createCanvas(__.element.width, __.element.height); }",
      "function draw() { circle(width / 2, height / 2, 80); }",
      "Pollock / Splatter → drag to paint; tune maxLineWidth, splatMax, or splatSpread in Parameters.",
      "const body = __.streams.list().find(stream => stream.kind === \"holistic\");\nconst nose = body?.feature(\"pose.nose\", { space: \"normalized\" });\nconst x = nose?.position?.x * width || mouseX;",
    ],
  },
  {
    id: "script-glsl",
    title: "GLSL quick reference",
    keywords: "glsl quick reference livecode shader fragment blank template uv fc r t resolution composition",
    body: "GLSL nodes render fragment shaders into a composable Livecode surface. The standard inputs include FC.xy for the fragment coordinate, r.xy for the surface resolution, and t for shared time. Layer, surface opacity, blend, and background use the shared Livecode compositor. Fluid Brush and Inkwash expose Emission as a script parameter: it lets scene or physics-debug geometry continuously inject and stir dye while pointer painting remains available.",
    examples: [
      "vec2 uv = (FC.xy - 0.5 * r.xy) / r.y;",
      "o = vec4(0.1 + 0.4 * sin(t + uv.x), 0.25, 0.8, 1.0);",
    ],
  },
  {
    id: "script-play-core",
    title: "Play Core quick reference",
    keywords: "play core quick reference ascii frame program settings fps cols rows main context buffer",
    body: "Play Core programs render one ASCII cell at a time into a rectangle or frame. Export settings for fps, cols, rows, color, and backgroundColor, then return a character or cell object from main(coord, context). Use pre and post around a shared buffer when a program needs a frame-wide pass.",
    examples: [
      "export const settings = { fps: 30 };",
      "export function main({ x, y }, context) { return Math.sin(x + context.time / 400) > 0 ? \"·\" : \" \"; }",
    ],
  },
  {
    id: "script-orca",
    title: "Orca quick reference",
    keywords: "orca quick reference livecode grid operators notes clock linked free step",
    body: "Orca is a compact frame-based livecoding grid. Type directly into cells, use uppercase operators to transform the grid, and use note operators such as : or % to emit events. Linked clocks follow Timeline; free clocks advance while the node runs.",
    examples: ["..:03C..\n..*....\n..R...."],
  },
  {
    id: "script-score",
    title: "Score quick reference",
    keywords: "score quick reference iannix curve cursor trigger run commands setcurve setspeed sessiontime",
    body: "Scores combine named curves, cursors, and triggers. Create and configure them with run() commands; cursors travel curves in score time and triggers emit messages at curve positions. Completion lists the supported syntax and runnable examples for the active command.",
    examples: [
      "run(\"add curve orbit\")",
      "run(\"add cursor traveler\")",
      "run(\"setCurve traveler orbit\")",
    ],
  },
  {
    id: "script-brush",
    title: "Brush quick reference",
    keywords: "brush quick reference modifier points globals tracks params apply bake channel",
    body: "Brush modifiers receive point tracks and a globals object, then return transformed or replacement tracks. Declare @param values for editable controls. Brush channels can map typed input streams to a live stroke and commit the visible result as one undoable freedraw.",
    examples: ["(points, globals) => {\n  return [points];\n}"],
  },
  {
    id: "script-media",
    title: "Media streams quick reference",
    keywords: "media streams quick reference holistic mediapipe feature inputs mapping actors scene normalized schlemmer pose blobatar avatar t-pose fallback mouse",
    body: "Media sources feed previews, Canvas capture, Holistic processors, actors, and typed streams. Source pixels and device handles stay local; semantic observations can be read by scripts or routed through Inputs, Mapping, and Brush. The MediaPipe · Schlemmer pose p5 example reads named pose landmarks and draws a Bauhaus-style figurine from discs, hoops, blocks, cylinders, and wedges, then uses a deterministic T-pose whenever no Holistic stream or completed frame is available. The MediaPipe · Blobatar p5 example uses the same pose.nose feature to move a cute blob and falls back to the mouse so it remains runnable without camera permissions.",
    examples: [
      "const body = __.streams.get(\"Holistic\");",
      "const finger = body.feature(\"left_hand.index_finger_tip\", { space: \"scene\" });",
      "const nose = body.feature(\"pose.nose\", { space: \"normalized\" });",
    ],
  },
  {
    id: "script-strudel",
    title: "Strudel quick reference",
    keywords: "strudel quick reference livecode pattern mini notation repl scheduler transport params voices",
    body: "Strudel nodes schedule pattern voices locally while sharing Underscores transport and Mixer routing. Use one $: statement per labelled voice, Mini Notation inside strings or backticks, and __.params for authored controls. Linked is the default; Free gives the node its own clock.",
    examples: [
      "$: note(\"<c e g>\").s(\"piano\")",
      ".color(pure(__.params.tint))",
    ],
  },
  {
    id: "script-manim",
    title: "Manim quick reference",
    keywords: "manim quick reference livecode animation scene cue create transform mathtex transport params",
    body: "Manim nodes run a scene with manim-web's public API plus scene, cue(), MANIM, and __. Use async scene.play calls for animation and optional cue pauses for teaching. Linked follows transport; Free uses the node scheduler.",
    examples: [
      "const shape = new Circle();",
      "await scene.play(new Create(shape));",
    ],
  },
  {
    id: "script-three",
    title: "Three.js quick reference",
    keywords: "three threejs webgl 3d scene camera controls blender option alt orbit pan zoom autofit frame wasd mediapipe holistic unicursal schlemmer costume ribbon renderer mesh geometry material unit cube torus knot orbiting spheres parameter dancing lights energy tick dispose livecode transport params obj zip archive mtl textures walt head",
    body: "Three.js nodes are independent bundled 3D Livecode scenes, not a Manim backend. `/live three` opens a blank source document; the Example menu provides Unit cube, Lit torus knot, Orbiting spheres, Parameter dancing lights, glTF model viewer, Animated glTF blendshape, Walt Head OBJ, MediaPipe Unicursal ribbon (3D), and MediaPipe Schlemmer costume (3D) starters. The two MediaPipe sources read named Holistic landmarks through __.streams and keep deterministic fallbacks until a frame is available. Source receives THREE, scene, camera, renderer, tick(callback), onDispose(callback), loadModel(url, options?), and __. `loadModel` is an allow-listed loader for OBJ, glTF/GLB, USD/USDZ, and ZIP archives containing an OBJ; ZIP models select a bounded in-memory OBJ entry and resolve companion MTL/textures when present. It returns `{ scene, animations, format }`, so an authored node can create an AnimationMixer and apply morphTargetInfluences without importing a loader or touching the DOM. Build geometry once, add it to scene, and animate with tick. Loaded model roots are automatically centered and framed from their bounds when the source leaves the default camera untouched; Option-Home restores that fitted view, while authored camera positioning opts out. Blender-style controls use Option-drag to orbit, Shift+Option-drag to pan, Ctrl+Option-drag to zoom, two-finger drag to orbit, Shift+two-finger drag to pan, and Ctrl+two-finger drag to zoom. When the patch is focused, W/S move forward/back relative to the current camera, A/D strafe, Q/E move vertically, Shift increases movement speed, and arrow keys orbit. Camera state is local runtime state. Linked follows Score transport; Free uses the node clock. Use onDispose for listeners or resources that are not attached to the scene graph. For local files, GLB is the most portable single-file choice; a local .gltf may need its companion .bin and textures available at resolvable URLs.",
    examples: [
      "const cube = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshNormalMaterial());\nscene.add(cube);",
      "tick(({ delta }) => { cube.rotation.y += delta; });",
      "// @param energy = 1.6 (0.4..3 step:0.1)\nconst light = new THREE.PointLight(0x8bd5ff, __.params.energy);\nscene.add(light);",
      "const asset = await loadModel(\"https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/AnimatedMorphCube/glTF-Binary/AnimatedMorphCube.glb\");\nscene.add(asset.scene);\nconst mixer = new THREE.AnimationMixer(asset.scene);\nif (asset.animations[0]) mixer.clipAction(asset.animations[0]).play();\ntick(({ delta }) => mixer.update(delta));",
      "const body = __.streams.list().find(stream => stream.kind === \"holistic\");\nconst nose = body?.feature(\"pose.nose\", { space: \"normalized\" });",
    ],
  },
  {
    id: "screencast-input",
    title: "Screencast input",
    keywords: "screencast input overlay keyboard shortcut click drag mouse gesture tool pointer tutorial presentation recording blender screencast keys",
    body: "Screencast input is a deliberately small, presentation-friendly view of the latest interactions. It shows shortcut presses, clicks, completed drags, scroll direction, and canvas tool changes without listing every high-frequency mouse sample. Modifier chords are kept together: holding Command for a click appears as one `⌘ left click` cue, while modifier-only keydown events are omitted. The current cue is emphasized with a compact keyboard keycap or mouse glyph, and the full overlay keeps a short four-cue trail; Minimal screencast input hides that trail and shows only the current cue. The header shows the active tool as an icon only, keeping the action readable without another label. Enable it from Settings → Interface, run `/screencast`, or press Command-Option-I on macOS (Ctrl-Alt-I elsewhere). Drag its header to reposition it; the position is remembered per browser. The close button and the same shortcut hide it again. The overlay does not change Excalidraw or livecode pointer ownership: interactive code, model, and media surfaces keep their own controls, while the canvas cursor changes to a pencil, hand, eraser, or shape cursor for the active Excalidraw tool. History still captures full press/move/release gesture samples when Canvas / performance input recording is enabled; during playback, the virtual cursor uses the matching recorded Excalidraw tool symbol and laser color. Screencast input is only the visual cue layer for live work and walkthroughs.",
    examples: [
      "/screencast",
      "Command-Option-I  →  toggle the overlay",
      "Settings → Interface → Screencast input",
    ],
  },
  {
    id: "media-3d-models",
    title: "3D model inputs",
    keywords: "3d model obj gltf glb usd usdz zip archive mtl textures media input drag drop model viewer animation mixer blendshape morph target preview",
    body: "Drop an OBJ, GLB/glTF, USD/USDZ, or ZIP archive containing an OBJ onto the canvas, or choose it from the Media panel's source picker. The file is stored in this browser's session catalog and becomes a normal Media source; drag the source icon onto the canvas to create a model preview. Canvas model previews are interactive by default: click the model to focus it, then use Option-drag to orbit, Shift-Option-drag to pan, Ctrl-Option-drag to zoom, or the matching two-finger trackpad gestures; W/S/A/D/Q/E and arrow keys work while focused. ZIP archives are unpacked in memory with bounded file and byte limits; scene.obj, model.obj, bunny.obj, or the first OBJ is selected, and companion MTL/textures are resolved when present. GLB is the easiest local format because it bundles geometry, materials, textures, and animations. glTF JSON files can reference external .bin and texture files, so a CORS-enabled URL or a complete resolvable file set is required. USD/USDZ is supported when the file is self-contained. Select a model source to choose a glTF animation, play or pause it, set loop and speed, and adjust discovered morph targets (blendshapes); these source controls update every preview using that source. Remote URLs must allow CORS. The Media panel includes the [Khronos glTF Sample Assets](https://github.khronos.org/glTF-Assets/) Damaged Helmet and Animated Morph Cube, CORS-enabled GitHub Utah Teapot and Stanford Bunny OBJ samples, and the [Three.js Walt Head OBJ](https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/models/obj/walt/WaltHead.obj). The legacy `stanford-bunny-zip` example id remains valid, but the bundled starter now uses a standalone CORS-enabled OBJ; dropped ZIP archives are still supported. `USD` is decoded with Three.js's bundled USDLoader; material and feature support depends on the source file.",
    examples: [
      "/model example=animated-morph-cube",
      "const asset = await loadModel(\"https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb\");",
      "asset.scene.traverse(object => object.morphTargetInfluences?.fill(0.5));",
    ],
  },
  {
    id: "script-markdown",
    title: "Markdown quick reference",
    keywords: "markdown quick reference livecode document headings lists code katex output code overlay",
    body: "Markdown nodes are deterministic local documents. Use normal Markdown headings, lists, code, and emphasis with inline or display KaTeX math. Output, Code, Code Overlay, and Code/Output views change presentation without changing the source.",
    examples: ["# A small patch\n\nUse **Markdown** and $x^2$ together."],
  },
  {
    id: "script-latex",
    title: "LaTeX quick reference",
    keywords: "latex quick reference livecode tex math typesetting katex output code",
    body: "LaTeX nodes provide deterministic local typesetting. Use inline $...$ or \\( ... \\), and display $$...$$ or \\[ ... \\]. Invalid math reports a local error while preserving the editable source.",
    examples: ["\\[ \\int_0^1 x^2 \\, dx = \\frac{1}{3} \\]"],
  },
  {
    id: "script-html",
    title: "HTML quick reference",
    keywords: "html quick reference livecode iframe sandbox css javascript window post onmessage output code",
    body: "HTML nodes run complete HTML, CSS, and scripts inside an isolated opaque-origin iframe. The token-scoped window.__.post/onMessage bridge is available for deliberate messages; parent DOM access, top navigation, and ambient privileges are blocked.",
    examples: ["<button onclick=\"window.__.post('clicked')\">Try it</button>"],
  },
  {
    id: "script-tixy",
    title: "Tixy quick reference",
    keywords: "tixy quick reference livecode expression grid sin cos t i x y params colors transport",
    body: "Tixy evaluates one compact JavaScript expression as (t, i, x, y) over a configurable dot grid. Add @param declarations for grid size and palettes, and use __.transport, __.pointer, __.events, and __.api for Underscores integration.",
    examples: ["sin(t + x / 4) * cos(t + y / 4)"],
  },
  {
    id: "panel-outliner",
    title: "Outliner",
    keywords: "outliner scene objects labels filter native excalidraw code score physics visibility lock delete selection",
    body: "Outliner is the compact inventory of the current patch. Search by label or id, switch filters for native, code, Score, and Physics objects, then select, hide, lock, or delete an object without changing its authored data. Unnamed native Excalidraw objects get type-specific, one-based scene-order labels such as stroke_0001; the four-digit suffix counts independently for each native type. Reordering or deleting objects can renumber generated labels, while double-clicking a row label creates an authored name that remains unchanged.",
  },
  {
    id: "panel-playlist",
    title: "Playlist",
    keywords: "playlist anchors cues triggers duration loop play pause next previous",
    body: "Playlist sequences cues and registered commands into a repeatable presentation. Add the current selection as an ordered anchor, or add an empty row and target it later. Each row stores its object ids, duration, cue metadata, and an optional trigger target.\n\nDrag rows to reorder, click to select, double-click to frame that anchor. Play advances using each row's duration; Step and the arrow keys advance manually; Loop repeats the list.\n\nA row can run a trigger when it activates. Command accepts a command id, name, or alias plus optional JSON arguments. Mini-script accepts palette slash forms. JavaScript accepts one trusted line against the public bridge. Command and Mini-script triggers receive the row's resolved target as elementId automatically, so livecode.node.stop addresses the chosen node without embedding a scene id.\n\nManim cues form an inner level: Next advances a pending cue before moving to the next anchor, and timed playback pauses at a pending manual cue rather than skipping the build. Walkthrough control uses ordinary Command triggers such as walkthrough.start or walkthrough.next.",
  },
  {
    id: "panel-properties",
    title: "Properties",
    keywords: "properties inspector selected object geometry style transform metadata",
    body: "Properties inspects the current selection. Edit geometry, style, transform, object metadata, and system-specific fields while keeping changes in the normal History and collaboration paths.",
  },
  {
    id: "panel-score",
    title: "Score",
    keywords: "score iannix curves cursors triggers roles timeline midi",
    body: "Score is the time-based curve, cursor, and trigger system. Use the Score panel to author roles and scripts, then let Timeline transport and mappings turn motion into events.",
  },
  {
    id: "panel-script",
    title: "Script",
    keywords: "script editor livecode p5 glsl orca strudel tixy markdown html svg code",
    body: "Script is the docked editor for whichever Livecode node is selected. It shows the same source document as the node on the canvas, so edits in either place are edits to one file.\n\nThe header selects the node by name before its kind. Double-click the name or press F2 to rename it; the adjacent frame button selects and frames that node on the canvas. Below it are Run and Stop, the compact clock toggle for Free or Linked, Auto-update, node typography, adapter-specific settings such as Strudel's frame visualizer, and any @param values the source declares.\n\nThe panel also carries an adapter-specific quick reference with the active kind's keyboard and runtime details, and reports compile and runtime status. Open it with /script or Ctrl+Alt+B.\n\nSee Livecode nodes for what a node is, Running, stopping, and updating for the edit and evaluation model, and the per-kind quick references under Scripting.",
  },
  {
    id: "panel-grid",
    title: "Grid",
    keywords: "grid snapping quantize spacing time units selection",
    body: "Grid controls visual snapping and time quantization. Adjust global spacing, toggle selection filtering, and quantize selected objects or timing without changing unrelated scene elements.",
  },
  {
    id: "panel-physics",
    title: "Physics",
    keywords: "physics bodies colliders constraints mappings play reset gravity rapier",
    body: "Physics is the inspector and transport for the relationship graph. Open it with /physics or /relations.\n\nWorld holds gravity in metres per second squared, viscosity, pixels per metre, and sim speed, plus play, pause, reset, and the option to sync every system to the music transport. Systems lists the worlds in the patch and holds the opt-in debug overlay and the collision-layer matrix. Bodies, Constraints, and Mappings list what you have authored, with the selected item's fields editable in place.\n\nThe compact floating Physics toolbar is the fast authoring surface for Weld, Axle, Spring, and Rope. Drag it by its atom icon, minimize it with Shift-double-click, close it with Option-double-click, and reopen it with /physicstoolbar or Ctrl+Alt+P. Its context menu switches between floating and a single-row top dock, and that preference persists locally.\n\nStart with Physics overview, then Bodies, colliders, and materials and Constraints. Posing, reset, and apply explains what Reset and Apply actually return to.",
  },
  {
    id: "panel-brush",
    title: "Brush",
    keywords: "brush modifiers channels stroke geometry tracks points javascript",
    body: "Brush applies reusable modifiers to strokes and tracks. Create a channel, choose its source and gate, preview mapped points, and apply or bake the result when the geometry is ready.",
  },
  {
    id: "panel-synth",
    title: "Synth",
    keywords: "synth expressive audio midi voice enable sound programs",
    body: "Synth routes expressive values to internal voices or MIDI destinations. Enable audio with a deliberate gesture, select a program, and keep routing changes inspectable in the patch.",
  },
  {
    id: "panel-media",
    title: "Media",
    keywords: "media camera video audio file source input capture record clip",
    body: "Media manages camera, video, audio, and imported sources. Select a source to preview it, connect it to an actor or processor, and use capture tools when you need a durable clip.",
  },
  {
    id: "panel-inputs",
    title: "Inputs",
    keywords: "inputs signals adapters midi osc events stream",
    body: "Inputs is the bridge for external signals and adapters. Register a source, inspect its latest values or events, and route those values to mappings, Brush channels, or scripts.",
  },
  {
    id: "panel-holistic",
    title: "MediaPipe Holistic",
    keywords: "mediapipe holistic pose hands face landmarks camera tracking",
    body: "Holistic turns a selected media source into semantic face, hand, and pose features. Choose display layers and confidence settings, then consume the normalized landmarks through actors or mappings.",
  },
  {
    id: "panel-mapping",
    title: "Media Mapping",
    keywords: "media mapping actors landmarks bindings signals target",
    body: "Media Mapping connects media features to canvas actors and downstream targets. Add a binding, set its gate and smoothing, and inspect the mapped value before arming it.",
  },
  {
    id: "panel-multiplayer",
    title: "Multiplayer",
    keywords: "multiplayer collaboration room peers share link identity",
    body: "Multiplayer shares authored patch state while keeping each person's camera, selection, and runtime playback local. Create or join a room, verify the peer list, and copy a room link when ready.",
  },
  {
    id: "panel-assistant",
    title: "AI Assistant",
    keywords: "assistant chat ai prompt commands webmcp models ollama",
    body: "AI Assistant can explain the current patch and call the same allowlisted command registry exposed by the palette and WebMCP. Inspect the active model and keep sensitive or destructive actions explicit.",
  },
  {
    id: "panel-history",
    title: "History",
    keywords: "history recording playback session baseline macro walkthrough",
    body: "History records command and presentation sessions with recoverable baselines. Use the History button or the Session recording shortcut (Command-Option-R on macOS by default; Ctrl-Alt-R elsewhere) to start or stop without recording the toggle itself. Enable Canvas / performance to retain pointer, mouse, pen, touch, wheel, click, or laser motion on the canvas and interactive performance surfaces. Enable UI events separately when a tutorial should retain panel, menu, editor, and settings interactions; keep it off for a clean rehearsal while you tweak the interface. Continuous move samples from the same pointer family are grouped into one readable clip within their scope; clicks and other discrete events stay separate, while a press/move/release drag is captured as one gesture clip. Gestures are sampled into bounded input actions and playback shows a glowing virtual cursor using the matching recorded Excalidraw tool symbol, cursor ring, or laser path; the Virtual cursor toggle controls that visual layer. Click an action to inspect it, Shift-click a range or Command/Ctrl-click individual actions to multi-select, then save the selection as one reusable macro. Pause, seek, replay, export, or turn a recording into a draft Walkthrough with the input cues preserved for editing.",
  },
  {
    id: "panel-walkthrough",
    title: "Walkthrough",
    keywords: "walkthrough guided tour lesson teaching narration cursor hint retry do it continue skip pace instant assertion baseline keep restore author steps cues history",
    body: "Walkthrough is the teaching and visible-automation layer. A walkthrough is an authored document of ordered steps with Markdown narration, optional Info copy, a semantic focus target, registered command cues, and a rule for when to move on.\n\nRunning one shows a glowing cursor over the targeted control, a draggable narration card, and learner controls. Continue moves on when you are ready. Check re-tests a step that waits on an assertion about the patch. Hint reveals the step's hint. Do it performs the step for you after you have tried it. Skip passes an optional step. Before playback starts, Underscores captures a complete baseline, so Stop offers Keep results or Restore starting patch, and reloading with an unfinished run offers the same choice.\n\nPace runs from slow to fast, plus Instant, which skips simulated typing and applies final values directly. A walkthrough can use a free clock or follow the transport; a transport-linked one shows read-only step markers in Timeline.\n\nThe panel is also the authoring surface: the step list, semantic target picker, cue and assertion editors, and validation messages. History → Create walkthrough converts the active recording into a draft, grouping actions that share a command group into one step. Permission-sensitive, destructive, file, MIDI, and audio cues always ask the learner first.\n\nOpen it with /walkthrough, /tour, or /guide. /welcome starts the bundled introduction.",
  },
  {
    id: "panel-settings",
    title: "Settings",
    keywords: "settings theme colors font shortcuts documentation autocomplete audio",
    body: "Settings contains interface, theme, editor, audio, transport, and documentation preferences. Changes use the active theme tokens and persist locally when they are personal presentation choices.",
  },
  {
    id: "panel-timeline",
    title: "Timeline",
    keywords: "timeline transport play pause seek tempo beats timecode frames loop clips selection block shift object lanes clip lanes tracks soundtrack cues mode",
    body: "Timeline is the shared transport for frame, timecode, and beat-based work. Play, pause, seek, set tempo, meter, and frame rate, mark loops, and follow linked Livecode nodes, physics worlds, arrangement clips, and walkthrough steps.\n\nDrag the ruler to seek, Command-drag to snap to major units, Command+Shift to snap to minor, and Shift-drag to mark a loop. The zoom strip pans and zooms the visible window; Command-click fits the score and Option-click fits the loop.\n\nTwo lane modes share that transport. **Object lanes** gives one lane per canvas object and shows recorded arrangement takes. **Clip lanes** makes the timeline a user-authored edit instead: add and rename tracks, reorder or mute and solo them, then drag History actions or Outliner objects onto a track. Clip timing is independent of the source object's layer; Livecode and media follow the clip's local playhead, and history command, scene, and MIDI cues fire when their clip starts.\n\nShift-click clips to select a contiguous range, Command/Ctrl-click to toggle individual clips, or drag across a lane area to make a block selection; selecting clips also selects their canvas objects. Expanded object takes show clips only in their object lanes, so the aggregate take row does not duplicate them.\n\nOpen it with /transport or Ctrl+Alt+T. See Timeline overview, Frames, timecode, and beats, Arrangement clips, Clip lanes, and Editing clips for the full model.",
  },
  {
    id: "panel-mixer",
    title: "Mixer",
    keywords: "mixer tracks instruments destinations gain mute solo midi audio",
    body: "Mixer organizes instrument tracks and destinations. Add a track, choose its instrument and output, then use mute, solo, and level controls while keeping source programs separate.",
  },
  {
    id: "panel-info",
    title: "Info",
    keywords: "info contextual hover focus quick reference documentation",
    body: "Info is the lightweight contextual reference and the fastest way to learn the interface while using it. Hover or focus any annotated control and Info shows its summary, syntax, or current status without changing the layout around it.\n\nIt also follows the active guided walkthrough step, so a running lesson can put explanatory copy somewhere stable while the narration card stays short.\n\nInfo stays deliberately compact. When you want the longer page, follow Open in Documentation rather than expecting the full catalog here. Open it with /info; it docks to the bottom alongside Timeline, Mixer, and Console.",
  },
  {
    id: "panel-console",
    title: "Console",
    keywords: "console events logs diagnostics performance fps poll export clear",
    body: "Console shows live events, diagnostics, and performance without adding them to the patch. Filter event types, inspect recent entries, and export logs when diagnosing a system.",
  },
  {
    id: "panel-documentation",
    title: "Documentation",
    keywords: "documentation help table contents search pages patches slash docs",
    body: "Documentation is the searchable learning library. The table of contents groups reference pages by section and lists bundled help patches and walkthroughs separately; search matches every term against titles, keywords, and body text at once, so physics midi finds the mapping pages.\n\nGetting started at the top of the panel launches the guided introduction. A help-patch entry can offer Start walkthrough, Insert patch, or both; a reference page with examples offers a copy button and, for Livecode kinds, a button that creates a node from that example directly.\n\nThe Aa control sets reading size between 10 and 24 px and is remembered locally. Open the panel with /docs, /documentation, or /help; it opens in the left dock by default and can move to the right, float, or join the bottom dock. /docs search <term> and /docs open <id> drive it from the command palette.",
  },
]);
